### ISSUE TITLE
Publish Helm charts via Github pages

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#1018]

**Comment by msivosuo** [comment]
@obaranov1 - would you be willing to continue your Helm chart work with this issue?

**Comment by obaranov1** [comment]
@mythi, @rmstoi chart for operator has 0.23.0 version instead of 0.24.0. This one should be fixed with a separate PR?

**Comment by rmstoi** [comment]
`make set-version` can be used to update version number of charts

**Comment by mythi** [comment]
> `make set-version` can be used to update version number of charts

One thing to note (and fix): our chart `version`s do not change currently. I think these should follow the release numbering too.

**Comment by mythi** [comment]
done, https://intel.github.io/helm-charts
