### ISSUE TITLE
Evaluate usage of Intel® Query Processing Library (Intel® QPL) in the IAA e2e tests

### ISSUE THREAD

**Issue by bart0sh** [intel/intel-device-plugins-for-kubernetes#1050]
The [Intel® Query Processing Library (Intel® QPL)](https://github.com/intel/qpl) is an open-source library to provide high-performance query processing operations on Intel CPUs. Intel® QPL is aimed to support capabilities of the new Intel® In-Memory Analytics Accelerator (Intel® IAA) available on Next Generation Intel® Xeon® Scalable processors, codenamed Sapphire Rapids processor, such as very high throughput compression and decompression combined with primitive analytic functions, as well as to provide highly-optimized SW fallback on other Intel CPUs. Intel QPL primarily targets applications such as big-data and in-memory analytic databases.

It may make sense to evaluate usage of QPL tests or sample applications in the project e2e tests.

**Comment by mythi** [comment]
https://github.com/intel/qpl/releases/tag/v0.2.0
https://intel.github.io/qpl/documentation/get_started_docs/system_requirements.html#accelerator-configuration-reference-link
