### ISSUE TITLE
Use initcontainer to configure DLB devices

### ISSUE THREAD

**Issue by bart0sh** [intel/intel-device-plugins-for-kubernetes#1053]
Some of the DLB usage scenarios (e.g. DPDK or libdlb using VFs) require additional setup, such as enabling VFs, binding them etc. This should be done in the initcontainer similarly to how it's done in the [QAT initcontainer](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/release-0.24/build/docker/intel-qat-initcontainer.Dockerfile#L58).

**Comment by mythi** [comment]
> This should be done in the initcontainer

as part of this item plan for the image publishing parts

**Comment by daixiang0** [comment]
I met the case that the number DLB device(`/dev/dlbN`) is random in the container, I use the first DLB device as default and support config, but it is impossible to confirm which random number would be used before config. Could we pin it in the initContainer as well? I really do not want to detect it with `ls`.

**Comment by bart0sh** [comment]
@daixiang0 Let's discuss this on the following example:

Let's say we have 8 pf devices: /dev/dlb0 - /dev/dlb7. Pods request them as dlb.intel.com/pf resources, work with them and release them after their jobs are done. DLB plugin allocates devices in their order (dlb0, dlb1, dlb2 ... dlb7). At some point all devices are allocated to workloads. The workload that uses /dev/dlb5 terminates and dlb5 becomes allocatable again. When new workload requests dlb.intel.com/pf, /dev/dlb5 device will be allocated for it.
How would you propose to pin the devices?

**Comment by daixiang0** [comment]
So now we can not get fake N in the container, right? In most cases, users do not care about the actual N as all they want is only one device. I know that keeps the actual N easy to debug, could we optimize it?

For now, I need to add detect logic to ensure the app work.

**Comment by mythi** [comment]
> I know that keeps the actual N easy to debug, could we optimize it?

I think the best thing to do is to set the provided devices to env variables for the container, something like:

```
DLB0=/dev/dlbX
DLBx=/dev/dlbY
...
```

This is similar what we do with QAT. See: https://github.com/intel/intel-device-plugins-for-kubernetes/blob/3c948cc106914c8e7149b6b5e74e05490f4e8a7f/demo/crypto-perf/run-dpdk-test#L13

Would that work?

**Comment by bart0sh** [comment]
Another way is to make one VF device and request it. This way you'll always get the same N.

**Comment by bart0sh** [comment]
@mythi would it make sense to sort [this output](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/dlb_plugin/dlb_plugin.go#L81) to make N a bit more predictable?

**Comment by mythi** [comment]
> @mythi would it make sense to sort [this output](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/dlb_plugin/dlb_plugin.go#L81) to make N a bit more predictable?

There's no predictability in how kubelet picks devices in Allocate because the registered device IDs are stored in Go maps and the order of elements in Go maps is random.

**Comment by daixiang0** [comment]
Is there an example for C++ to detect it? I can not use bash script in initContainer since it is already a sidecar.

**Comment by mythi** [comment]
> Is there an example for C++ to detect it? I can not use bash script in initContainer since it is already a sidecar.

Are you asking how the proposal I made would work or how to detect devices in `/dev/dlbX`?

**Comment by daixiang0** [comment]
I ask how to detect devices in `/dev/dlbx` using c++ code?

**Comment by mythi** [comment]
> I ask how to detect devices in `/dev/dlbx` using c++ code?

Before going into this question, let's try to conclude what the device plugin can do to make it as easy as possible. Can you comment on the proposal I made? (btw, maybe start with a new issue first because this conversation is not related to this issue)

**Comment by daixiang0** [comment]
I agree.

**Comment by daixiang0** [comment]
Is it possible to expose an ENV to make applications easily detect?

**Comment by mythi** [comment]
Yes (see the QAT example)

**Comment by daixiang0** [comment]
Could you give a link?

**Comment by mythi** [comment]
The plugin does not support it yet.

**Comment by daixiang0** [comment]
> The plugin does not support it yet.

Will it come in Sep.2022?

**Comment by mythi** [comment]
> > The plugin does not support it yet.
> 
> Will it come in Sep.2022?

Most likely no, unless you are able to contribute the changes. The first thing is to submit an issue about what the ask is so we could get it to our Q4 planning.

There are ways to workaround the gap you are observing so not having it should not be a blocker.
