### ISSUE TITLE
Broken deployments doc links

### ISSUE THREAD

**Issue by eero-t** [intel/intel-device-plugins-for-kubernetes#1058]
This page: https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/

Leads here: https://intel.github.io/intel-device-plugins-for-kubernetes/README.html

While rest of the links there seem to work, **all** the links in "Workload Authors" section are broken: https://intel.github.io/intel-device-plugins-for-kubernetes/README.html#workload-authors

PS. "Related code" section paragraph is missing period (".") from the end.

**Comment by byako** [comment]
The sphinx extension (sphinx_markdown_tables) used to render the table into html seem to convert it so before the links could be handled by recommonmd and expanded with github URLs, see https://github.com/ryanfox/sphinx-markdown-tables/issues/18, - that's the reason the links point to the docs.
