### ISSUE TITLE
Multiple afu modes

### ISSUE THREAD

**Issue by yanceliyuqi** [intel/intel-device-plugins-for-kubernetes#113]
There are 2 fpga afu on one of our hosts with uuid `18b79ffa-2ee5-4aa0-96ef-4230dafacb5f` and `d8424dc4-a4a3-c413-f89e-433683f9040b` like the attachment named afu.png. 
While, if we run fpga_plugin in `af` mode, we can found only one afu (18b79ffa-2ee5-4aa0-96ef-4230dafacb5f) been registed into k8s, like the attachment name registed_afu.png.
![afu](https://user-images.githubusercontent.com/35280160/47347632-3d0cc480-d6e2-11e8-84f7-1df98991898e.png)
![registed_afu](https://user-images.githubusercontent.com/35280160/47347633-3da55b00-d6e2-11e8-92a2-619aed306f5f.png)

**Comment by bart0sh** [comment]
@yanceliyuqi can you check please if the latest master fixes this issue?
