### ISSUE TITLE
e2e: add compression tests for e2e-qat4

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#1138]
For `QAT Gen4` tests, we want to check `qat.intel.com/dc` resources are registered. For this task, there's no need to run any compress workload requesting that resource, though.

**Comment by msivosuo** [comment]
Slow progress, need to be pushed to Q4.

**Comment by msivosuo** [comment]
@ozhuraki - please submit a draft pr this week to gather feedback from the broader team.

**Comment by mythi** [comment]
beware that after #1234 `qat.intel.com/dc` resources are no longer available

/cc @hj-johannes-lee

**Comment by mythi** [comment]
fixed by @hj-johannes-lee
