### ISSUE TITLE
kubernetes application

### ISSUE THREAD

**Issue by yanceliyuqi** [intel/intel-device-plugins-for-kubernetes#114]
I just allocated one region of fpga for my pod. While , in my pod, i can see all of fpga on this host. The attachment named cern.yml is the detail of my pod, and the 1.png is the output of `kubectl get pod -o yaml`, and the 2.png is the output of `lspci | grep 9c[45]` running in my pod, 3.png for `fpgainfo fme` in my pod and 4.png for `fpgainfo port`in my pod.

![1](https://user-images.githubusercontent.com/35280160/47347721-69c0dc00-d6e2-11e8-9535-f77394be1a71.png)
![2](https://user-images.githubusercontent.com/35280160/47347722-6a597280-d6e2-11e8-9d11-23fed01bae3b.png)
![3](https://user-images.githubusercontent.com/35280160/47347725-6b8a9f80-d6e2-11e8-8677-d056c77385d4.png)
![4](https://user-images.githubusercontent.com/35280160/47347726-6b8a9f80-d6e2-11e8-8f2f-112494be0113.png)
![cernyml](https://user-images.githubusercontent.com/35280160/47347923-e2c03380-d6e2-11e8-89cc-11e0354ebe0a.png)

**Comment by bart0sh** [comment]
Yes, you can see all FPGAs and everything that is in /sys/class as /sys is readable in the container. However, you shouldn't be able to use any devices that you didn't allocate.

I'm closing this. Please reopen if you see not allocated fpga device nodes in /dev/. You can check them using this command on the host and inside container:
```
ls /dev/intel-fpga-*
```
