### ISSUE TITLE
Communication Channels?

### ISSUE THREAD

**Issue by asim-reza** [intel/intel-device-plugins-for-kubernetes#1171]
Hey Everyone!
I wanted to contribute to this project as well as intel/edge-conductor... But as is the case for the main K8s project I couldnt find means to communicate and coordinate with other contributors , e.g slack... I was wondering if I just missed it, or there is none, or if so is it internal to intel?

**Comment by mythi** [comment]
@asim-reza thanks for your issue! you can find me in slack to chat but we currently don't have any project channel.

**Comment by asim-reza** [comment]
thank you!
