### ISSUE TITLE
namespaces "intelfpgaplugin-system" not found

### ISSUE THREAD

**Issue by AhmedMaj** [intel/intel-device-plugins-for-kubernetes#1212]
Hello,
when I reach to this step I got this issue.

`$ kubectl apply -k https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/fpga_plugin/overlays/af?ref=v0.24.0
customresourcedefinition.apiextensions.k8s.io/acceleratorfunctions.fpga.intel.com configured
customresourcedefinition.apiextensions.k8s.io/fpgaregions.fpga.intel.com configured
clusterrole.rbac.authorization.k8s.io/intelfpgaplugin-manager-role configured
clusterrole.rbac.authorization.k8s.io/intelfpgaplugin-node-getter unchanged
clusterrolebinding.rbac.authorization.k8s.io/intelfpgaplugin-get-nodes unchanged
clusterrolebinding.rbac.authorization.k8s.io/intelfpgaplugin-manager-rolebinding unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/intelfpgaplugin-mutating-webhook-configuration configured
Error from server (NotFound): error when creating "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/fpga_plugin/overlays/af?ref=v0.24.0": namespaces "intelfpgaplugin-system" not found
Error from server (NotFound): error when creating "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/fpga_plugin/overlays/af?ref=v0.24.0": namespaces "intelfpgaplugin-system" not found
Error from server (NotFound): error when creating "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/fpga_plugin/overlays/af?ref=v0.24.0": namespaces "intelfpgaplugin-system" not found
Error from server (NotFound): error when creating "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/fpga_plugin/overlays/af?ref=v0.24.0": namespaces "intelfpgaplugin-system" not found
Error from server (NotFound): error when creating "https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/fpga_plugin/overlays/af?ref=v0.24.0": namespaces "intelfpgaplugin-system" not found`

**Comment by mythi** [comment]
ack. there's some problem which I believe comes from the base which does not add the custom namespace:

```
$ kubectl apply --dry-run=server -k deployments/fpga_plugin/base/
clusterrole.rbac.authorization.k8s.io/node-getter created (server dry run)
clusterrolebinding.rbac.authorization.k8s.io/get-nodes created (server dry run)
Error from server (NotFound): error when creating "deployments/fpga_plugin/base/": namespaces "system" not found
```

**Comment by msivosuo** [comment]
@bart0sh - do you have time to take a look?

**Comment by bart0sh** [comment]
@msivosuo sure, will look
