### ISSUE TITLE
ginkgo upgrade fails

### ISSUE THREAD

**Issue by bart0sh** [intel/intel-device-plugins-for-kubernetes#1249]
Dependabot upgrade PRs[1,2] for ginkgo and gomega fail with this error:

vendor/k8s.io/kubernetes/test/e2e/framework/test_context.go:355:14: suiteConfig.EmitSpecProgress undefined (type "github.com/onsi/ginkgo/v2/types".SuiteConfig has no field or method EmitSpecProgress)

1. [build(deps): bump github.com/onsi/ginkgo/v2 from 2.4.0 to 2.5.0](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1239)
2. [build(deps): bump github.com/onsi/gomega from 1.24.0 to 1.24.1](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1243)

**Comment by mythi** [comment]
@bart0sh we will need to wait k8s to move to 2.5.0 first. Patrick is working on it in https://github.com/kubernetes/kubernetes/pull/113538 but it will be accepted after 1.26.
