### ISSUE TITLE
Update accel-config version for accel-config-demo

### ISSUE THREAD

**Issue by vranar-int** [intel/intel-device-plugins-for-kubernetes#1353]
accel-config tool has recently been updated to version 4.0
(https://github.com/intel/idxd-config/releases/tag/accel-config-v4.0)

Current docker image for accel-config demo is using 3.5.2.

**Comment by mythi** [comment]
> Current docker image for accel-config demo is using 3.5.2.

do you have a particular image in mind where 4.0 is preferred?

**Comment by mythi** [comment]
@vranar-int that's good input! 

@ozhuraki PTAL

**Comment by vranar-int** [comment]
It is also likely the accel-config tool is used with the device plugin in general so it might be worth checking if an overall update is required. The mentioned image is one place I can 100% confirm because of our use.

**Comment by eero-t** [comment]
That uses Debian unstable, but `accel-config` version there is still at 3.5.3.  Debian unstable is rolling distro, so it will update eventually.

**Comment by mythi** [comment]
`accel-config-demo` image uses a version we can control and I've asked @ozhuraki to update
