### ISSUE TITLE
when using with camera input which require privileged securityContext GPU cannot be found

### ISSUE THREAD

**Issue by mwright-pivotal** [intel/intel-device-plugins-for-kubernetes#1378]
spec:
      containers:
      - env:
        - name: VIDEO_INPUT
          value: "0"
        - name: ACCELERATION_DEVICE
          value: GPU
        image: harbor.services.edge.wrightcode.io:9443/apps/computer-vision-inferencing-app-default@sha256:49c5495e6bc26d6996aae0c64a6ec3e53e4b75e452c539cee49a22424ae4c6af
        name: workload
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        resources:
          limits:
            gpu.intel.com/i915: 1
        securityContext:
          privileged: true
      serviceAccountName: default
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0

container can access GPU as long as I don't use privileged: true.  however this is needed to access a USB camera on the host.  This is an edge computing use case.  Device is Intel NUC, NUC11TNKv7

**Comment by mythi** [comment]
> however this is needed to access a USB camera on the host.

I would suggest to use a device plugin for this resource too, for example: `generic-device-plugin`.

**Comment by eero-t** [comment]
This seems odd, as privileged should provide container with access to all system calls and capabilities, and write access to all device files (which is the reason why privileged mode is typically rejected in production clusters as too much of a security hole).

@mwright-pivotal in which way container cannot access the GPU, is the device file is not there, or not writable?

Which container engine (docker, container, cri-o...) and container runtime (runc, crun...) you are using?

What are the GPU device access rights on the node host, and what user ID container uses?

@tkatila Could you check whether GPU works in privileged container in general?

**Comment by mwright-pivotal** [comment]
@eero-t I will provide further details.  I am able to access the USB device and the GPU using the suggestion that @mythi provided without privileged: true.  

The GPU appears under /dev/dri/render on the host OS.  I am using containerd/runc in this K8s distro (small binary vmware kubernetes).  I am using the validation job in this repo (demo/intelgpu-job.yaml)

**Comment by tkatila** [comment]
@eero-t quick test with privileged didn't show anything weird. Though, using both gpu-plugin and privileged is kinda pointless, as privileged exposes the gpu devices also.

**Comment by eero-t** [comment]
> quick test with privileged didn't show anything weird. Though, using both gpu-plugin and privileged is kinda pointless, as privileged exposes the gpu devices also.

Sure,  I just wanted confirmation that this pointless config works, as it should.  GPU plugin causing privileged mode not to work sounded really odd.

> I am using containerd/runc in this K8s distro (small binary vmware kubernetes).

@mwright-pivotal VMWare = containers are running under VM?   How you're exposing GPUs to the VM?

**Comment by tkatila** [comment]
@mwright-pivotal are there any opens or can we close this?

**Comment by tkatila** [comment]
Closing.
