### ISSUE TITLE
backport qat and gpu commits to 0.26 branch

### ISSUE THREAD

**Issue by tkatila** [intel/intel-device-plugins-for-kubernetes#1394]
Operator:
#1397 

QAT:
https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1343
https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1390

GPU:
https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1363
https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1371

**Comment by mythi** [comment]
done
