### ISSUE TITLE
Out of date DLB package in dlb demo images

### ISSUE THREAD

**Issue by vranar-int** [intel/intel-device-plugins-for-kubernetes#1405]
The DLB driver package used in demonstration images is out of date. Current upstream version of the driver is 8.3.0 while the version in the demo images is set to 8.0.0. This causes issues on Sapphire Rapids platform where the demo container terminates with failure with error status stating **DLB2_ST_FEATURE_UNAVAILABLE** even though the dlb.intel.com resource is properly detected by the device plugin in K8s and test pod is properly scheduled.

**Comment by mythi** [comment]
We'll see if we can update but since we don't publish this image and you will need to build it too, you can override the existing 8.0.0 version using `--build-arg` for  `DLB_TARBALL` and `DLB_TARBALL_SHA256` to unblock your testing

**Comment by vranar-int** [comment]
Thank you for quick response. We'll implement the fix using the `--build-arg` into our test suite.
