### ISSUE TITLE
Why the vpu device plugin no need set default docker runtime?

### ISSUE THREAD

**Issue by gaoyangcaiji** [intel/intel-device-plugins-for-kubernetes#1413]
why the vpu not same as the nvidia gpu？Does vpu don't neet mount the driver files and device files?i am confused with this,hope your answer. Thank you

**Comment by mythi** [comment]
> Does vpu don't neet mount the driver files and device files?

That's what you get from the VPU device plugin and the underlying container runtime uses that information. We have device plugins for each different *Intel* device.
