### ISSUE TITLE
deployment with kustomize: fix deprecated bases, patchesStrategicMerge, vars

### ISSUE THREAD

**Issue by hj-johannes-lee** [intel/intel-device-plugins-for-kubernetes#1446]
When deploying a plugin or an operator, some warning messages below apper:
>  \# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
  \# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
  \# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your 
Kustomization automatically.

**Comment by mythi** [comment]
is this with 1.27 `kubectl`? It's always good to describe the environment how to reproduce

**Comment by hj-johannes-lee** [comment]
Yes, it is after 1.27...!
Actually all e2e tests just show the warnings already.
https://github.com/intel/intel-device-plugins-for-kubernetes/actions/runs/5378970240/jobs/9759514263#step:6:115

**Comment by tkatila** [comment]
I peeked at this. bases->resources and patchesStrategicMerge->patches seems doable. vars->replacements isn't looking good.
