### ISSUE TITLE
prepare device plugin API changes for CDI injection

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#1457]
Kubernetes `KEP4009: Add CDI Devices to device plugin API` got approved. 

It will be added as an alpha feature but we could look into adding the support to our framework and see what use-cases it enables (e.g., FPGA deallocate)

**Comment by bart0sh** [comment]
Considering that CDI support for Device Plugins has been graduated to Beta in Kubernetes 1.29, this task becomes more important. Moreover, it can be a show stopper for graduating CDI support for DP to GA as this requires [Gathering feedback from at least 2 device plugin vendors that CDI support works for them](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4009-add-cdi-devices-to-device-plugin-api#beta-to-ga-graduation).

@mythi @tkatila Can we prioritise this issue?

**Comment by tkatila** [comment]
@bart0sh patches are welcome. :)

Is there a time frame for the feedback?

**Comment by bart0sh** [comment]
I'm going to add CDI support for FPGA plugin in near future.

**Comment by bart0sh** [comment]
@tkatila 
> Is there a time frame for the feedback?

I'm sorry for missing your question. We're hoping to get [CDI support for device plugins](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4009-add-cdi-devices-to-device-plugin-api) graduated to GA in [the next Kubernetes release](https://www.kubernetes.dev/resources/release/).
It would help a lot to achieve this if [this PR](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1745) is merged.

When it's merged, I'll update the feedback info of [the KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4009-add-cdi-devices-to-device-plugin-api) and you can add your feedback there as review comments. But first we should merge the implementation.

**Comment by mythi** [comment]
closed by #1745
