### ISSUE TITLE
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe001

### ISSUE THREAD

**Issue by wonbin2011** [intel/intel-device-plugins-for-kubernetes#1462]
hi , 
as the follow: 
https://asciinema.org/a/0xa888OjktVyz6xf0RSQ6Pi0w

when i run   the sgx-sdk-demo   out-of-proc:
`
kubectl pply -k intel-device-plugins-for-kubernetes-0.23.0/deployments/sgx_enclave_apps/overlays/sgx_ecdsa_aesmd_quote/ -n sgx-ecdsa-quote
`
and the result :
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/7733385/dca55b71-3eb8-4fd0-abc7-0382b97be627)

![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/7733385/9714042f-6ad2-44a8-b9b2-a27bef12b78c)

out of proc:
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/7733385/0c3e3522-afb8-417c-9caf-10d100cc7d9e)

k8s: 1.23
os: ubuntu22.04

Any pointers are greatly appreciated! Thank you!!

**Comment by wonbin2011** [comment]
> 

sorry to reply lately.  I thought  inteldeviceplugin version 0.23.0  corresponds  to cluster version 1.23, maybe i am wrong,
is there any key word  that releated to intel sgx ?

**Comment by wonbin2011** [comment]
@tkatila 

dmesg log:
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/7733385/dae48203-deaf-427e-af25-759748a2d10a)
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/7733385/900a9f60-9db9-4940-97e2-d768347ad582)

**Comment by mythi** [comment]
@wonbin2011 I believe your setup is missing the PCCS configuration. Quote generation needs to talk to a PCCS.

**Comment by wonbin2011** [comment]
> @wonbin2011 I believe your setup is missing the PCCS configuration. Quote generation needs to talk to a PCCS.

could please provide any  infomation about setting up pccs ?

**Comment by mythi** [comment]
Intel's DCAP docs are here:
https://download.01.org/intel-sgx/sgx-dcap/1.16/linux/docs/

**Comment by wonbin2011** [comment]
> Intel's DCAP docs are here: https://download.01.org/intel-sgx/sgx-dcap/1.16/linux/docs/

thank you  very much

**Comment by mythi** [comment]
@wonbin2011 did you get the issue fixed? I'm planning to close this since it's not device plugins related.
