### ISSUE TITLE
qat: add support for device heartbeat status

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#1480]
https://git.kernel.org/pub/scm/linux/kernel/git/herbert/cryptodev-2.6.git/commit/?id=359b84f8db942ef46d24de8aa397790c3fae22e0

**Comment by tkatila** [comment]
What level of support would it be? Read status and report device Healthiness based on it? Allow changing the heartbeat interval via configmap option?

**Comment by mythi** [comment]
> Read status and report device Healthiness based on it? 

Yes, each scan checks for -1 in `status` and sets pluginapi `Health` accordingly.

> Allow changing the heartbeat interval via configmap option?

I think not, at list for starters. The interval is fixed on `4xxx` and if configuration is needed, a custom initcontainer could do it.
