### ISSUE TITLE
qat plugin init container crashes with provisioning config

### ISSUE THREAD

**Issue by vbedida79** [intel/intel-device-plugins-for-kubernetes#1542]
### Summary
On OCP 4.12.26 with device plugins 0.26.2, when using the provisioning configmap with complete crypto or compress resources the qat plugin's init container crashes. 
### Details
For the first time when using this configuration, there are no issues with plugin. 
If we delete and recreate with same or new resource (cy/dc), we notice this issue. The error is inconsistent and work around is unloading/reloading drivers. The resources not being cleaned up properly, could it be the cause? Thanks!

```
16
tee: '/sys/bus/pci/devices/0000:6b:00.0/sriov_numvfs': Invalid argument
16
tee: '/sys/bus/pci/devices/0000:e8:00.0/sriov_numvfs': Invalid argument
```

**Comment by mythi** [comment]
@hj-johannes-lee can you reproduce?

**Comment by hj-johannes-lee** [comment]
I cannot reproduce it..
Could you just show what you did?

**Comment by mythi** [comment]
@vbedida79 we cannot reproduce. is this still an issue on your side?

**Comment by vbedida79** [comment]
Checked it on OCP 4.14 OCP, did not notice any error. Thanks. 
Closing this issue.
