### ISSUE TITLE
qat-initcontainer does not have LICENSE installed in root/licenses dir

### ISSUE THREAD

**Issue by chaitanya1731** [intel/intel-device-plugins-for-kubernetes#1604]
qat-initcontainer does not have LICENSE installed in root `/licenses/intel-device-plugins-for-kubernetes/LICENSE` dir which results in preflight failure for openshift certification. 

sgx example here -  https://github.com/intel/intel-device-plugins-for-kubernetes/blob/3739fcbd7fa0705c1d873afd20fa10301b1a5d14/build/docker/intel-sgx-initcontainer.Dockerfile#L53
Can we do this for the qat-initcontainer too. Thanks

**Comment by hj-johannes-lee** [comment]
@mythi Sure, let me fix.!
