### ISSUE TITLE
Feature to make variations of init container Dockerfiles for other platforms like OCP

### ISSUE THREAD

**Issue by mregmi** [intel/intel-device-plugins-for-kubernetes#1616]
Currently there is only one variation of Dockerfile for initcontainers. But they differ a bit between vanilla Kubernetes and OpenShift. So we currently modify the Dockerfile to customize for OpenShift. It would be nice if we can do `make dockerfile` to create a separate Dockerfiles for OCP (when run with ENV variable). Some differences are below.
* we use different base image (RedHat UBI)
* We cannot use the currently used toybox as it modifies base image's /bin
* We need some custom commands to install packages as UBI image is small and does not contain everything we need.

**Comment by mythi** [comment]
> it is grep, findutils and pciutils

`find` is not covered but there it is needed?

**Comment by mregmi** [comment]
Actually find is not needed for this. it was for driver image so not needed here.

**Comment by mythi** [comment]
Fixed by #1615
