### ISSUE TITLE
QAT VF kernel driver name is c62xvt, not c6xxvt  for C62X device

### ISSUE THREAD

**Issue by rzang-intel** [intel/intel-device-plugins-for-kubernetes#1645]
Code : https://github.com/intel/intel-device-plugins-for-kubernetes/blob/ff41eb8b42388fb6ff9ad32392d4a9490db5b659/cmd/qat_plugin/dpdkdrv/dpdkdrv.go#L69

According to the latest kernel code:
https://github.com/torvalds/linux/tree/master/drivers/crypto/intel/qat

The VF driver name is c62xvt, not c6xxvt. 
This mistake prevents the plugin from being installed on C62X chipset.

**Comment by mythi** [comment]
> The VF driver name is c62xvt, not c6xxvt.
> This mistake prevents the plugin from being installed on C62X chipset.

Even if the driver name says `c62xvf`, it shows up as `c6xxvf` when loaded on the system: `/sys/bus/pci/drivers/c6xxvf/` and that's what this plugin parameter matches. 

What is the error you are seeing?

**Comment by rzang-intel** [comment]
Yes, you are right. The driver name did show up as "c6xxvf" in the system. Thanks for correcting me.
The problem I am facing is the intel-qat-plugin container in CrashLoopBackOff state due to (from its log):
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/78188748/2eb15c89-9c8f-40df-8371-8b7ff8abef47)

Previously I thought it was unbinding using the wrong driver name. However, it is not the case as you pointed out.
The device 0000:3d:01:0 is the PF device. 
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/78188748/0f9e77cc-1b28-4dd3-81ce-e4cb2bef4c7c)
So could you please shad some light on why it is unbinding the PF device and why it failed?

BTW, I am using release v0.22.0.

**Comment by rzang-intel** [comment]
Yes, you are right. The driver did show up as "c6xxxvf" in the system.
The problem I am facing is the intel-qat-plugin container in CrashLoopBackOff state due to (from its log):
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/78188748/a6ae6c63-197e-4e8f-b27d-c462956b662d)
0000:3d:01:0 is the first VF:
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/78188748/01626530-d9e4-4b2f-92e7-d449e026c950)

Previously I thought it was because the wrong driver name. However, it is not the case as you pointed out. Could you please also shed some light on why it kept failing on unbinding the VF driver?
BTW, I am using release v0.22.0

**Comment by rzang-intel** [comment]
Removed the VF driver. It stops at this error:
![image](https://github.com/intel/intel-device-plugins-for-kubernetes/assets/78188748/1c483d64-7b04-4f81-9a14-59c1178a3c42)

**Comment by mythi** [comment]
Are you running Ubuntu? On Apparmor enabled systems the plugin must be deployed using the `unconfined` annotation to avoid Apparmor blocking the sysfs writes. We don't have it properly documented but see https://github.com/intel/intel-device-plugins-for-kubernetes/tree/main/deployments/qat_plugin/overlays/apparmor_unconfined

**Comment by rzang-intel** [comment]
Well, it always is beneficial to ask the master! Thanks Mikko! It resolves my problem!
