### ISSUE TITLE
Intel QAT service script issues and restriction

### ISSUE THREAD

**Issue by juggarnautss** [intel/intel-device-plugins-for-kubernetes#1646]
We are enabling QAT services on our platforms where we have to give configuration option to user to enable no of VF/endpoints for a specific QAT(PF) device. Once the endpoints are enabled on platform, we will using intel plugin operator to install the QAT plugin. However, on the platform side we found following restriction/constraints wrt intel /etc/init.d/qat_service script :

1. /etc/init.d/qat_service script does not support configuring user defined number of QAT VFs other than max supported ie. 16.

2. /etc/init.d/qat_service script does not support starting a specific QAT device, by default it starts all the devices irrespective of how many endpoint configuration files are present or not.

3. During multiple start or restart of single PF using intel qat_service script, mapping of device name with their configuration files is changing. 
      Example: 
      Initial VF mapping=> 
      PF0 : qat_dev2(0000:f3:00.1) maps to  4xxxvf_dev0.conf  
      PF1 : qat_dev18(0000:f7:00.1) maps to  4xxxvf_dev16.conf  
      After restart PF0 or PF1=> 
      PF0 : qat_dev2(0000:f7:00.1) maps to  4xxxvf_dev0.conf  
      PF1 : qat_dev18(0000:f3:00.1) maps to  4xxxvf_dev16.conf  

Please assist us in resolving these limitation.

**Comment by mythi** [comment]
> However, on the platform side we found following restriction/constraints wrt intel /etc/init.d/qat_service script :

What's this script? I don't think that's applicable to this project (since `4xxxvf_devX.conf` refers to the out-of-tree installation which is not covered by the QAT plugin).

In general, on 1) 16 is the only available value on 4xxx.

**Comment by juggarnautss** [comment]
> We are enabling QAT services on our platforms where we have to give configuration option to user to enable no of VF/endpoints for a specific QAT(PF) device. Once the endpoints are enabled on platform, we will using intel plugin operator to install the QAT plugin. However, on the platform side we found following restriction/constraints wrt intel /etc/init.d/qat_service script :
> 
> 1. /etc/init.d/qat_service script does not support configuring user defined number of QAT VFs other than max supported ie. 16.
> 2. /etc/init.d/qat_service script does not support starting a specific QAT device, by default it starts all the devices irrespective of how many endpoint configuration files are present or not.
> 3. During multiple start or restart of single PF using intel qat_service script, mapping of device name with their configuration files is changing. 
>    Example: 
>    Initial VF mapping=> 
>    PF0 : qat_dev2(0000:f3:00.1) maps to  4xxxvf_dev0.conf  
>    PF1 : qat_dev18(0000:f7:00.1) maps to  4xxxvf_dev16.conf  
>    After restart PF0 or PF1=> 
>    PF0 : qat_dev2(0000:f7:00.1) maps to  4xxxvf_dev0.conf  
>    PF1 : qat_dev18(0000:f3:00.1) maps to  4xxxvf_dev16.conf
> 
> Please assist us in resolving these limitation.

Posted in wrong github. Hence closing the issue.

**Comment by juggarnautss** [comment]
Posted in wrong github. Hence closing the issue.
