### ISSUE TITLE
Create new demos based on OpenVINO

### ISSUE THREAD

**Issue by kad** [intel/intel-device-plugins-for-kubernetes#169]
For FPGA and maybe GPU demos we can use something from https://software.intel.com/en-us/openvino-toolkit/choose-download to create more spectacular demos

**Comment by khrd** [comment]
FYI
https://github.com/khrd/openvino_container_for_PAC

**Comment by bart0sh** [comment]
FYI
https://gitlab.devtools.intel.com/ebartosh/openvino-docker

**Comment by linjiach** [comment]
code that is not reviewed yet: https://gitlab.devtools.intel.com/ssp-demos/kubernetes/fpga-device-plugin/blob/master/Dockerfile.openvino_fpga.ubuntu

I put together a dockerfile for dcp1.2 and openvino this could be used to run openvino benchmark etc.

**Comment by tkatila** [comment]
Closing as part of cleanup activity: Old issue.
