### ISSUE TITLE
Publish accel-config-demo image to docker hub

### ISSUE THREAD

**Issue by alysondeives** [intel/intel-device-plugins-for-kubernetes#1692]
It would be great if accel-config-demo image is also published to docker hub. Currently we need to build it from source.

**Comment by mythi** [comment]
Due to legacy reasons we have two "demo" images (crypto-perf and opae-nlb-demo) published but that's not a common pattern for the images we use in our e2e tests so it's likely we keep this as it is today.

**Comment by mythi** [comment]
closing as "wont fix"
