### ISSUE TITLE
Evaluate usage of FPGA/GPU/QAT devices on nodes with SELinux enabled.

### ISSUE THREAD

**Issue by kad** [intel/intel-device-plugins-for-kubernetes#170]
In order to support properly usage of our device plugins with OpenShift on top of CentOS/RHEL hosts, we need to validate that SELinux policies are not conflicting with any of the devices.

**Comment by mythi** [comment]
there's an ongoing effort to adjust `selinux-container` policies as part of the OCP certification. the work is done outside of this repo so closing it here.
