### ISSUE TITLE
Intel 14th-gen Meteor Lake

### ISSUE THREAD

**Issue by Kiryuumaru** [intel/intel-device-plugins-for-kubernetes#1706]
**Describe the support request**
I would like to add new `Intel 14th-gen Meteor Lake` as resources into my pod by:
```
resources: 
  limits:
    gpu.intel.com/i915: 1
```
but pod wont initialize because of lacking resources.

**System (please complete the following information if applicable):**
 - OS version: [e.g. Ubuntu 22.04]
 - Kernel version: [e.g. Linux 5.15]
  - Device plugins version: [e.g. v0.29.0]
 - Hardware info: [e.g. SPR with QAT]

**Comment by tkatila** [comment]
Hi @Kiryuumaru could please describe your environment? Which k8s version, which gpu plugin you installed etc.?

**Comment by tkatila** [comment]
Closing. Please reopen with more details if this is still an issue.
