### ISSUE TITLE
Evaluate operator approach to distribute out-of-tree kernel drivers and tools for accelerators

### ISSUE THREAD

**Issue by kad** [intel/intel-device-plugins-for-kubernetes#171]
For FPGA and QAT we want to evaluate means on how to distribute and automate lifecycle of out-of-tree kernel modules and tools via operators.

Reference:
https://github.com/zvonkok/special-resource-operator

**Comment by ipuustin** [comment]
I'm interested in this. The linked resource operator appears to work using PCI ids. Do you know if it can be  used for FPGA or QAT use cases without changes if a suitable driver container was created?
