### ISSUE TITLE
Status of this Project

### ISSUE THREAD

**Issue by onedr0p** [intel/intel-device-plugins-for-kubernetes#1759]
Hi @rdower / @mythi  / team

It looks like this repo was made private, and then public again losing all its stars. Then we see in the commit history that was going to be archived which was then also undone. What is happening here, do you have any insights?

**Comment by eero-t** [comment]
Several bugs were also closed & re-opened  (many times)...   Some automation script gone wild?

**Comment by onedr0p** [comment]
Yeah something smells of an automation script going rogue

https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1751

**Comment by mythi** [comment]
@onedr0p the status of this project is unchanged (i.e., no plans to archive it and the work continues). your observation about what happened is correct but there were no bad actors involved. Github does not gracefully handle the case where a repo is made private and then reverted but we've gotten things almost back to where we were originally. apologies
