### ISSUE TITLE
How to use the allocation policy

### ISSUE THREAD

**Issue by aq2013** [intel/intel-device-plugins-for-kubernetes#1774]
**Describe the support request**
We created gpu device plugin  with allocation-policy balanced and shared-dev-num 2.  One node with one of Intel GPU Flex 140 GPU card. So the cluster have 2 node with  Flex 140 GPU card and each node have 2 gpu.intel.com/i915.

Now we deployed 2 gpu applications, each requests 1 gpu.intel.com/i915. As I understand, when the allocation-policy is balanced  ( " balanced mode spreads workloads among GPU devices"), these 2 applications should be scheduled to 2 different nodes with gpu cards.  But we found all 2 applications were scheduled to the same node.

device-plugin:
```
Args:
      -shared-dev-num=2
      -enable-monitoring
      -allocation-policy=balanced
      -v=5
```

worknode-104:
<img width="414" alt="截屏2024-07-08 下午2 43 41" src="https://github.com/intel/intel-device-plugins-for-kubernetes/assets/20430537/c2e5af47-af98-46d8-b55d-c654cf40a288">

worknode-105:
<img width="417" alt="截屏2024-07-08 下午2 44 31" src="https://github.com/intel/intel-device-plugins-for-kubernetes/assets/20430537/94a1704b-607b-4b78-82a8-a2e96c8c77d3">

2 applications on one node:
<img width="606" alt="截屏2024-07-03 下午4 32 02" src="https://github.com/intel/intel-device-plugins-for-kubernetes/assets/20430537/5a1999ba-ce00-49d0-baf2-e835904aa53f">

**System (please complete the following information if applicable):**
 - OS version: [e.g. Ubuntu 22.04]
 - Kernel version: [e.g. Linux 5.15]
  - Device plugins version: [e.g. v0.29.0]
 - Hardware info: [e.g. Flex 140 gpu]

**Comment by tkatila** [comment]
Hi @aq2013 and thanks for the issue.

>Now we deployed 2 gpu applications, each requests 1 gpu.intel.com/i915. As I understand, when the allocation-policy is balanced ( " balanced mode spreads workloads among GPU devices"), these 2 applications should be scheduled to 2 different nodes with gpu cards. But we found all 2 applications were scheduled to the same node.

GPU plugin works at node level so it can only affect the GPU selection among the GPUs that are in its control. Thus the "balanced" mode only applies within the node not over the whole cluster. e.g, when user deploys two Pods and they happen to be scheduled to the same node, GPU plugin will deploy one to GPU1 and the other to GPU2.

Depending on your goal, I can think of two ways to get where you'd want to be:
- Inter Pod anti-affinity rules (https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity) - prevent scheduler from scheduling a Pod to a node that already has the same type of Pod.
  - Maybe not usable if you'd eventually want to schedule two similar Pods to one node.
- GAS' `balancedResource` - does resource balancing (=GPU) over the cluster (https://github.com/intel/platform-aware-scheduling/blob/master/gpu-aware-scheduling/README.md#gas-scheduler-extender)
  - Depending on your cluster access rights, might be hard to install. Requires changes to the scheduler config on the host.

Also, Flex 140 should have two GPUs per a physical card. With "shared-dev-num" == 2, there should be 4 `i915` resources.

**Comment by aq2013** [comment]
Thanks for the reply.  Now we added the anti-affinity rules to schedule  Pods to different nodes. I will close this issue.
