### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by hsyrjaos** [intel/intel-device-plugins-for-kubernetes#1843]
git clone https://github.com/intel/intel-device-plugins-for-kubernetes.git
Cloning into 'intel-device-plugins-for-kubernetes'...
remote: Enumerating objects: 23655, done.
remote: Counting objects: 100% (5929/5929), done.
remote: Compressing objects: 100% (994/994), done.
remote: Total 23655 (delta 5162), reused 5205 (delta 4905), pack-reused 17726 (from 1)
Receiving objects: 100% (23655/23655), 15.69 MiB | 21.69 MiB/s, done.
Resolving deltas: 100% (13610/13610), done.
hsyrja@hs-work:~/works/repos/tests$ cd intel-device-plugins-for-kubernetes/
hsyrja@hs-work:~/works/repos/tests/intel-device-plugins-for-kubernetes$ make
cd cmd/dlb_plugin; go build -tags ""
cd cmd/dsa_plugin; go build -tags ""
cd cmd/fpga_admissionwebhook; go build -tags ""
cd cmd/fpga_crihook; go build -tags ""
cd cmd/fpga_plugin; go build -tags ""
cd cmd/fpga_tool; go build -tags ""
cd cmd/gpu_fakedev; go build -tags ""
cd cmd/gpu_levelzero; go build -tags ""
# github.com/intel/intel-device-plugins-for-kubernetes/cmd/gpu_levelzero
ze.c:19:10: fatal error: ze_api.h: No such file or directory
   19 | #include <ze_api.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:115: gpu_levelzero] Error 1

**Comment by tkatila** [comment]
This is because we integrated a component which has dependencies to levelzero.

This should help:
```
sudo apt-get update
sudo apt-get install -y libze1 libze-dev
```
