### ISSUE TITLE
Enable TopologyInfo in pkg/deviceplugin

### ISSUE THREAD

**Issue by krsna1729** [intel/intel-device-plugins-for-kubernetes#216]
Allow passing NUMA information when using pkg/deviceplugin

https://github.com/kubernetes/kubernetes/blob/11678fb1c029ee1f3c7223e87d339b2d0016fdb8/pkg/kubelet/apis/deviceplugin/v1beta1/api.proto#L84-L101

**Comment by mythi** [comment]
Done.
