### ISSUE TITLE
 VCA1(VCA1283LVV) support？

### ISSUE THREAD

**Issue by mdjxyf** [intel/intel-device-plugins-for-kubernetes#225]
I installed the plug-in in the VCA card , but when I started gpu_plugins, I saw the following error through debug mode:
![image](https://user-images.githubusercontent.com/55568070/65294771-cd24e980-db91-11e9-9050-fbd4bfe4be1a.png)

Is VCA1 supported?

**Comment by kad** [comment]
From debug output that you shown, yes, device plugin was able to detect correctly `card0`.
Do you observe any issue with it if your workload tries to use the GPU?

**Comment by mdjxyf** [comment]
Thank, Kad.  Since I am new to the VCA card, do you have any suggestions for me to verify if the GPU is working?

**Comment by mdjxyf** [comment]
Each NODE node on VCA card communicates with NAT. Can it be bridged? If not, how does the node on VCA communicate with other physical hosts?

**Comment by kad** [comment]
@mdjxyf to verify that it is working, you can do `kubectl describe node XXXX` where your plugin runs. you should see resources exposed by plugin. 
For network question, unfortunately I'll not be able to help much here, haven't tried myself this particular version of the card. In theory, on the host OS, you can do bridge from your VCA "veth" to host's physical ethernet.

**Comment by mdjxyf** [comment]
Thank , Kad . On the node of VCA, install the node program of k8s, but after installing docker, the node cannot be connected through SSH after rebooting. I guess it's because docker has modified the network part, but I don't know where it is. Do you know?

**Comment by mythi** [comment]
it seems the GPU plugin was working correctly, closing but please reopen if still valid
