### ISSUE TITLE
opae-nlb-demo: install content in /usr/local

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#227]
in order to better separate between "base image" and add-on content.

**Comment by mythi** [comment]
@hectoragb would you be able to help with this?

**Comment by hectoragb** [comment]
Sure, @mythi

**Comment by mythi** [comment]
@hectoragb please submit the PR for review

**Comment by hectoragb** [comment]
@mythi Could you please close this one as per https://github.com/intel/intel-device-plugins-for-kubernetes/pull/239?
