### ISSUE TITLE
Current doc is all about how to deploy a device plugin. Could you please add more description about the device and how to use the plugin? 

### ISSUE THREAD

**Issue by LuyaoZhong** [intel/intel-device-plugins-for-kubernetes#233]

**Comment by mythi** [comment]
@LuyaoZhong demo folder has several application deployments that request resources provided by the plugins. The screencast videos linked in the README might also help.

**Comment by mythi** [comment]
@LuyaoZhong is this still valid?

**Comment by LuyaoZhong** [comment]
@mythi Sorry for this late reply. I mean could you please add more description about what every step is doing(e.g. for FPGA, what is admission webhook doing, what is CRI-O hook doing), some basic notions about the devices, and some useful links which can help newbies/me. :D

**Comment by msivosuo** [comment]
In addition we should:
- explain the two drivers, two modes
- Update the screencast.

**Comment by msivosuo** [comment]
Updated screencast: https://github.com/intel/intel-device-plugins-for-kubernetes/pull/262

**Comment by grahamwhaley** [comment]
I also think we could do with a bunch more info on the front page of the repo describing more of what the framework is and how it plugs into k8s (personally I like diagrams as well).
The way the ToC entries for the sub-components (fpga, gpu etc.) leap off to other documents further down the tree is really strange as well - the ToC should point to sections on the main page, that then probably have a brief description and then leap off to the sub-section.

We need to make the front (landing) page more informative and easy for folks to leap off from - it is the first thing they will see when they land in the repo.

**Comment by grahamwhaley** [comment]
See #268 for improvements to FPGA documentation.

**Comment by msivosuo** [comment]
@kad, @rojkov -could you take a look at #268, thanks!

**Comment by msivosuo** [comment]
Closing as this is now addressed, @LuyaoZhong please reopen or create a new issue if you still feel there are gaps.
