### ISSUE TITLE
QAT plugin kerneldrv mode is not passed to Docker build

### ISSUE THREAD

**Issue by ipuustin** [intel/intel-device-plugins-for-kubernetes#234]
It seem that the `kerneldrv` build tag might not get propagated correctly to the QAT plugin Docker build.

    $ make BUILDTAGS=kerneldrv intel-qat-plugin
    
    ... <snip part of build logs> ...
    
    Step 9/18 : ARG TAGS_KERNELDRV=
     ---> Running in 6ac3ccad1fbd
    
    ... <snip part of build logs> ...

    
    Successfully tagged intel/intel-qat-plugin:devel
    $ docker run -it --rm intel/intel-qat-plugin:devel -mode kernel
    kernel mode is not supported in this build. Use 'kerneldrv' build tag to have this mode enabled. Exiting...

**Comment by mythi** [comment]
@ipuustin the dockefile arg is `TAGS_KERNELDRV` but it seems `build-image.sh` resets `BUILDTAGS`...
