### ISSUE TITLE
Should update the API version cause Kubernetes v1.16 has deprecated some API version.

### ISSUE THREAD

**Issue by xxinran** [intel/intel-device-plugins-for-kubernetes#240]
Refer to https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/, DaemonSet, Deployment(in the extensions/v1beta1 and apps/v1beta2 API groups) has been
migrated to use the apps/v1 API, available since v1.9.  

I met this issue when create intel-fpga-webhook-deployment, please see my code update below:
![image](https://user-images.githubusercontent.com/40164212/71073579-9e7fd480-21bb-11ea-88b7-b418c0c42747.png)

**Comment by bart0sh** [comment]
This has been taken care of. [The PR](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/238) is under review.
