### ISSUE TITLE
Required v0.18 Release Checks

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#251]
Complete required release checks.

**Comment by mythi** [comment]
Checklist:

- [ ] run validation on master
- [ ] create release-0.18 branch
- [ ] `make set-version TAG=0.18.0` + commit
- [ ] `make lock-images` + commit
- [ ] draft release notes, review
- [ ] update master README for supported versions
- [ ] final validation
- [ ] publish release
