### ISSUE TITLE
Kustomize

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#254]
Goals:
1. qat plugin to be deployable with kubectl apply -k qat_plugin/VERSION (VERSION being devel or a release tag)
2. gpu plugin to be deployable with kubectl apply -k gpu_plugin/..., possibly configurable command line parameters if needed
3. fpga plugin to be deployable with kubectl apply -k fpga_plugin/..., different kustomizations for different run modes (preprogrammed vs orchestrated)
4. and support for other plugins (Movidius) as well

**Comment by askervin** [comment]
More detailed goals:

1. qat plugin to be deployable with `kubectl apply -k qat_plugin/VERSION` (`VERSION` being devel or a release tag)

2. gpu plugin to be deployable with `kubectl apply -k gpu_plugin/...`, possibly configurable command line parameters if needed

3. fpga plugin to be deployable with `kubectl apply -k fpga_plugin/...`, different kustomizations for different run modes (preprogrammed vs orchestrated)

**Comment by askervin** [comment]
Reasoning for the work:
- provide end users an easy and consistent way to deploy the plugins and add their own customizations
- improve deployment maintainability by removing duplication

**Comment by mythi** [comment]
@askervin FYI, deployments from the repo works:

```
kubectl apply -k github.com/intel/intel-device-plugins-for-kubernetes.git/deployments/qat_dpdk_app/test-crypto1?ref=master
```

**Comment by mythi** [comment]
> (VERSION being devel or a release tag)

This may not be necessary since we can already do

```
$ kubectl kustomize github.com/intel/intel-device-plugins-for-kubernetes.git/deployments/qat_dpdk_app/test-crypto1?ref=release-0.15
$ kubectl kustomize github.com/intel/intel-device-plugins-for-kubernetes.git/deployments/qat_dpdk_app/test-crypto1?ref=master
```

**Comment by grahamwhaley** [comment]
I did consider doing the direct-from-URL deploys in the docs updates, which in the case of using the default images and setup would avoid pulling the sources down. But, one change at a time....

**Comment by askervin** [comment]
PRs contributing to this issue:
- QAT plugin - PR #286
- GPU plugin - PR #288
