### ISSUE TITLE
OpenShift on Clear + Device Plugins verification

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#256]
Setup OpenShift and Device plugins.

**Comment by msivosuo** [comment]
@CraigSterrett - is this still a valid issue?

**Comment by msivosuo** [comment]
Needs to be split to plugin specific operators. Let's revisit this after cluster add-on feature merged to K8s.

**Comment by CraigSterrett** [comment]
This is still valid as of today.

**Comment by msivosuo** [comment]
Closing, not valid anymore.
