### ISSUE TITLE
FPGA Device Plugin Validation on real hardware

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#293]
Validate FPGA device plugin on real hardware.

**Comment by msivosuo** [comment]
@bart0sh - please document the remaining tasks.

**Comment by bart0sh** [comment]
Remaining tasks:
- run full FPGA test. Currently only preprogrammed mode is tested.
- integrate with github CI: maintainers should be able to trigger PR tests by adding /ok-to-test comment. Logs should be visible in the PR

**Comment by bart0sh** [comment]
Status update: FPGA test successfully runs. integration with github actions is progressing.
