### ISSUE TITLE
GPU device plugin validation on real hardware

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#294]
Validate GPU plugin on real hardware.

**Comment by rojkov** [comment]
The existing E2E test for GPU tests if a pod requesting an Intel GPU resource actually gets scheduled on a node. For details see https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/test/e2e/gpu/gpu.go.
So far I've validated it on a single node cluster and the node being a NUC with Intel Iris GPU.
