### ISSUE TITLE
ubuntu-demo-openvino: install from deb packages

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#309]
...instead of downloading the bug .tar.gz, install the necessary packages from the openvino apt repo.

**Comment by mythi** [comment]
looks like the hddl packages are not available :/

**Comment by mythi** [comment]
@alekdu looks like OpenVINO 2020.2 from the apt/yum repos have the HDDL tools now available. Can you see if this can be fixed by updating to that release?

**Comment by alekdu** [comment]
Okay, let me try.

**Comment by alekdu** [comment]
https://github.com/intel/intel-device-plugins-for-kubernetes/pull/367
