### ISSUE TITLE
QAT: non root workloads

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#319]
Change QAT plugin to allow cluster admins specify which non-root user is allowed to use VFIO devices

**Comment by msivosuo** [comment]
@mythi - please add CRI-O and containerd prs as a comment, thanks!

**Comment by msivosuo** [comment]
containerd pr: https://github.com/containerd/containerd/pull/5122

**Comment by mythi** [comment]
cri-o pr: https://github.com/cri-o/cri-o/pull/4620
