### ISSUE TITLE
Intel Device Operator 

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#324]
Implement one lifecycle operator for all intel device plugins
- [x] Study 
- [x] Support and documentation for GPU and QAT

**Comment by msivosuo** [comment]
@rojkov, @askervin  - would either of you have time to pick this up? @mythi can provide background information.

**Comment by askervin** [comment]
@msivosuo , I'll talk with @mythi about this.

**Comment by msivosuo** [comment]
@askervin  - I talked with @rojkov already and we agreed he's taking a look. But thanks anyway!

**Comment by rojkov** [comment]
braindump on possible functionality: https://docs.google.com/document/d/1raZQKpCIgqmdiI41hCNJL1kmZAYz8xJMzy7OsLJNyVQ/edit#heading=h.fnlack9sz6iv

**Comment by msivosuo** [comment]
https://github.com/intel/intel-device-plugins-for-kubernetes/pull/376
