### ISSUE TITLE
ci: coverage: consider adding code coverage check to CI

### ISSUE THREAD

**Issue by grahamwhaley** [intel/intel-device-plugins-for-kubernetes#346]
With improvements to code coverage, it may be prudent to see if the CI can be made to check for code coverage regression (and at least report them, if not even fail the CI).

Over on Kata Containers for instance https://codecov.io/ is used to do the check. Some links then:

Pull results at the end of a CI run: https://github.com/kata-containers/agent/blob/44b84a6e6515164c5dd8ec735d69ddf6b9f61313/.travis.yml#L34

Get a badge: https://raw.githubusercontent.com/kata-containers/proxy/5223906c9d3453d9a0ae31f36b2508ee720671fa/README.md

You may want to consult with @jodh-intel and @chavafg to help figure out exactly how it is hooked/integrated into the repos. iirc, it's not immediately obvious ;-)

**Comment by mythi** [comment]
Github actions submit coverage reports:
https://github.com/intel/intel-device-plugins-for-kubernetes/blob/26f1a0efa34c3ff9faa8c84154b0ea16d5505f06/.github/workflows/ci.yaml#L66-L67
