### ISSUE TITLE
WARNING: GetTopologyInfo: device /dev/uio5 doesn't exist

### ISSUE THREAD

**Issue by lehongwen** [intel/intel-device-plugins-for-kubernetes#347]
**[root@k8s220 intel-device-plugins-for-kubernetes]# kubectl get pods -o wide**
NAME                     READY   STATUS    RESTARTS   AGE     IP            NODE     NOMINATED NODE   READINESS GATES
intel-qat-plugin-zk84x   1/1     Running   0          7m33s   172.20.0.13   k8s220   <none>           <none>
qat-dpdk                 1/1     Running   0          5s      172.20.0.14   k8s220   <none>           <none>

**[root@k8s220 intel-device-plugins-for-kubernetes]# kubectl logs pod/intel-qat-plugin-zk84x**
QAT device plugin started in 'dpdk' mode
01:01.0 device: corresponding DPDK device detected is uio0
WARNING: GetTopologyInfo: device /dev/uio0 doesn't exist
01:01.1 device: corresponding DPDK device detected is uio1
WARNING: GetTopologyInfo: device /dev/uio1 doesn't exist
01:01.2 device: corresponding DPDK device detected is uio2
WARNING: GetTopologyInfo: device /dev/uio2 doesn't exist
01:01.3 device: corresponding DPDK device detected is uio3
WARNING: GetTopologyInfo: device /dev/uio3 doesn't exist
01:02.0 device: corresponding DPDK device detected is uio4
WARNING: GetTopologyInfo: device /dev/uio4 doesn't exist
01:02.1 device: corresponding DPDK device detected is uio5
WARNING: GetTopologyInfo: device /dev/uio5 doesn't exist
01:02.2 device: corresponding DPDK device detected is uio6
WARNING: GetTopologyInfo: device /dev/uio6 doesn't exist
01:02.3 device: corresponding DPDK device detected is uio7
WARNING: GetTopologyInfo: device /dev/uio7 doesn't exist
DEBUG manager.go:110 Received dev updates: {map[generic:map[01:01.0:{Healthy [{/dev/uio0 /dev/uio0 rw {} 0}] [{/sys/class/uio /sys/class/uio/uio0/device false {} 0}] map[QAT1:0000:01:01.0] <nil>} 01:01.1:{Healthy [{/dev/uio1 /dev/uio1 rw {} 0}] [{/sys/class/uio /sys/class/uio/uio1/device false {} 0}] map[QAT2:0000:01:01.1] <nil>} 01:01.2:{Healthy [{/dev/uio2 /dev/uio2 rw {} 0}] [{/sys/class/uio /sys/class/uio/uio2/device false {} 0}] map[QAT3:0000:01:01.2] <nil>} 01:01.3:{Healthy [{/dev/uio3 /dev/uio3 rw {} 0}] [{/sys/class/uio /sys/class/uio/uio3/device false {} 0}] map[QAT4:0000:01:01.3] <nil>} 01:02.0:{Healthy [{/dev/uio4 /dev/uio4 rw {} 0}] [{/sys/class/uio /sys/class/uio/uio4/device false {} 0}] map[QAT5:0000:01:02.0] <nil>} 01:02.1:{Healthy [{/dev/uio5 /dev/uio5 rw {} 0}] [{/sys/class/uio /sys/class/uio/uio5/device false {} 0}] map[QAT6:0000:01:02.1] <nil>} 01:02.2:{Healthy [{/dev/uio6 /dev/uio6 rw {} 0}] [{/sys/class/uio /sys/class/uio/uio6/device false {} 0}] map[QAT7:0000:01:02.2] <nil>} 01:02.3:{Healthy [{/dev/uio7 /dev/uio7 rw {} 0}] [{/sys/class/uio /sys/class/uio/uio7/device false {} 0}] map[QAT8:0000:01:02.3] <nil>}]] map[] map[]}
Start server for generic at: /var/lib/kubelet/device-plugins/qat.intel.com-generic.sock
Device plugin for generic registered
DEBUG server.go:100 Started ListAndWatch for generic
DEBUG server.go:90 Sending to kubelet []
DEBUG server.go:90 Sending to kubelet [&Device{ID:01:01.3,Health:Healthy,Topology:nil,} &Device{ID:01:02.0,Health:Healthy,Topology:nil,} &Device{ID:01:02.1,Health:Healthy,Topology:nil,} &Device{ID:01:02.2,Health:Healthy,Topology:nil,} &Device{ID:01:02.3,Health:Healthy,Topology:nil,} &Device{ID:01:01.0,Health:Healthy,Topology:nil,} &Device{ID:01:01.1,Health:Healthy,Topology:nil,} &Device{ID:01:01.2,Health:Healthy,Topology:nil,}]
**### 01:01.0 device: corresponding DPDK device detected is uio0
WARNING: GetTopologyInfo: device /dev/uio0 doesn't exist
01:01.1 device: corresponding DPDK device detected is uio1
WARNING: GetTopologyInfo: device /dev/uio1 doesn't exist
01:01.2 device: corresponding DPDK device detected is uio2
WARNING: GetTopologyInfo: device /dev/uio2 doesn't exist
01:01.3 device: corresponding DPDK device detected is uio3
WARNING: GetTopologyInfo: device /dev/uio3 doesn't exist**

**[root@k8s220 usertools]# kubectl describe node k8s220 | grep qat.intel.com/generic**
 qat.intel.com/generic:  8
 qat.intel.com/generic:  8
  qat.intel.com/generic  0           0
[root@k8s220 usertools]# 

**intel-qat-plugin-config.yaml**
apiVersion: v1
kind: ConfigMap
metadata:
  name: intel-qat-plugin-config
data:
  DPDK_DRIVER: "igb_uio"
  KERNEL_VF_DRIVERS: "c3xxxvf"
  MAX_NUM_DEVICES: "16"
  DEBUG: "true"

[root@k8s220 usertools]# ./dpdk-devbind.py -s

Network devices using kernel driver
===================================
0000:03:00.0 'I210 Gigabit Network Connection 1533' if=enp3s0 drv=igb unused=igb_uio 
0000:04:00.0 'I210 Gigabit Backplane Connection 1537' if=enp4s0 drv=igb unused=igb_uio *Active*
0000:05:00.0 'I210 Gigabit Backplane Connection 1537' if=enp5s0 drv=igb unused=igb_uio 
0000:07:00.0 'Ethernet Connection X553 Backplane 15c2' if=enp7s0f0 drv=ixgbe unused=igb_uio 
0000:07:00.1 'Ethernet Connection X553 Backplane 15c2' if=enp7s0f1 drv=ixgbe unused=igb_uio 
0000:09:00.0 'Ethernet Connection X553 Backplane 15c2' if=enp9s0f0 drv=ixgbe unused=igb_uio 
0000:09:00.1 'Ethernet Connection X553 Backplane 15c2' if=enp9s0f1 drv=ixgbe unused=igb_uio 

Crypto devices using DPDK-compatible driver
===========================================
0000:01:01.0 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:01.1 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:01.2 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:01.3 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:02.0 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:02.1 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:02.2 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:02.3 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf

Crypto devices using kernel driver
==================================
0000:01:00.0 'Atom Processor C3000 Series QuickAssist Technology 19e2' if= drv=c3xxx unused=qat_c3xxx,igb_uio 

Other Crypto devices
====================
0000:01:01.4 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:01.5 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:01.6 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:01.7 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:02.4 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:02.5 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:02.6 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:02.7 'Device 19e3' unused=qat_c3xxxvf,igb_uio

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================

**[root@k8s220 usertools]# ./dpdk-devbind.py -s**

Network devices using kernel driver
===================================
0000:03:00.0 'I210 Gigabit Network Connection 1533' if=enp3s0 drv=igb unused=igb_uio 
0000:04:00.0 'I210 Gigabit Backplane Connection 1537' if=enp4s0 drv=igb unused=igb_uio *Active*
0000:05:00.0 'I210 Gigabit Backplane Connection 1537' if=enp5s0 drv=igb unused=igb_uio 
0000:07:00.0 'Ethernet Connection X553 Backplane 15c2' if=enp7s0f0 drv=ixgbe unused=igb_uio 
0000:07:00.1 'Ethernet Connection X553 Backplane 15c2' if=enp7s0f1 drv=ixgbe unused=igb_uio 
0000:09:00.0 'Ethernet Connection X553 Backplane 15c2' if=enp9s0f0 drv=ixgbe unused=igb_uio 
0000:09:00.1 'Ethernet Connection X553 Backplane 15c2' if=enp9s0f1 drv=ixgbe unused=igb_uio 

Crypto devices using DPDK-compatible driver
===========================================
0000:01:01.0 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:01.1 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:01.2 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:01.3 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:02.0 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:02.1 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:02.2 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf
0000:01:02.3 'Device 19e3' drv=igb_uio unused=qat_c3xxxvf

Crypto devices using kernel driver
==================================
0000:01:00.0 'Atom Processor C3000 Series QuickAssist Technology 19e2' if= drv=c3xxx unused=qat_c3xxx,igb_uio 

Other Crypto devices
====================
0000:01:01.4 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:01.5 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:01.6 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:01.7 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:02.4 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:02.5 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:02.6 'Device 19e3' unused=qat_c3xxxvf,igb_uio
0000:01:02.7 'Device 19e3' unused=qat_c3xxxvf,igb_uio

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================

**[root@k8s220 usertools]# lscpu** 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    1
Core(s) per socket:    12
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 95
Model name:            Intel(R) Atom(TM) CPU C3808 @ 2.00GHz
Stepping:              1
CPU MHz:               800.000
CPU max MHz:           2000.0000
CPU min MHz:           800.0000
BogoMIPS:              3999.98
Virtualization:        VT-x
L1d cache:             24K
L1i cache:             32K
L2 cache:              2048K
NUMA node0 CPU(s):     0-11

**Comment by mythi** [comment]
@lehongwen this is a warning that we don't find topology information for `uio_igb` devices. Are you not able to use `vfio-pci`?
