### ISSUE TITLE
CI: consider using `chronic` to reduce log output

### ISSUE THREAD

**Issue by grahamwhaley** [intel/intel-device-plugins-for-kubernetes#348]
The CI logs can be pretty big, and mostly full of information about things that worked, that are expected to work, like installing and building components necessary to run the actual tests.
This can make finding the actual error quite difficult. It is probably more difficult in Travis than in Jenkins (which is broken into stages, making it easier to narrow in).
As we are transitioning from Travis to Actions, we should contemplate if the situation still exists, and if so, consider using [`chronic`](http://manpages.ubuntu.com/manpages/xenial/man1/chronic.1.html) to wrap the common expected-to-work items (package installs, compiles etc.), so they are benign unless they fail. This may make perusing the CI failure logs easier.

**Comment by mythi** [comment]
> As we are transitioning from Travis to Actions, we should contemplate if the situation still exists, and if so,
> consider using chronic to wrap the common expected-to-work items (package installs, compiles etc.),

Actions seems to work fine on this so closing.
