### ISSUE TITLE
VPU Plugin Go unit tests coverage

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#349]
@alekdu we're improving Go unit test coverage for our plugins.

VPU plugin coverage is <50%. Please check if that could be improved still.

Steps:
1.  `make test WHAT=cmd/vpu_plugin`
2. review `cmd/vpu_plugin/coverage.html`

There's not much code in the plugin so while many things are already covered the coverage is poor.

Some ideas:
1. move `sharedDevNum` checking to `newDevicePlugin` and add a test case for 0 value
2. test without `/var/tmp/hddl_service.sock`
3. test `Scan()` API as it was just added in FPGA plugin
4. `os.Exit(1)` is now redundant 

Other:
`/var/tmp/hddl_service.sock` is not cleaned up after testing

**Comment by alekdu** [comment]
hmm... I will look into this.

**Comment by alekdu** [comment]
https://github.com/intel/intel-device-plugins-for-kubernetes/pull/352 please review

**Comment by mythi** [comment]
these changes were made...
