### ISSUE TITLE
fpga: prestart hook is deprecated by OCI

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#369]
According to [OCI hooks spec](https://github.com/opencontainers/runtime-spec/blob/master/config.md#posix-platform-hooks), `prestart` hook is deprecated. Should we look into moving `createRuntime`?

**Comment by bart0sh** [comment]
We should wait until runc 1.0 is released and probably wait a bit more until they stabilise new hooks.

**Comment by mythi** [comment]
agree. I submitted this based on what I learnt today so that we keep an eye on it

**Comment by msivosuo** [comment]
Not relevant -> closing. Reopen if needed.
