### ISSUE TITLE
Intel SGX Device Plugin

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#379]
Write Intel SGX Device Plugin and the necessary deployment/configs (including node-feature-discovery settings):

- [x] Deliver deployment artifacts to register SGX EPC memory as Kubernetes Extended Resources and document usage via NFD 
- [x] Deliver NFD configuration and documentation to deploy NFD to get SGX enabled nodes labeled.
- [x] Deliver a Dockerfile and Job deployment to demonstrate Enclave creation in Kubernetes.

**Comment by ipuustin** [comment]
PR for SGX device plugin and NFD source plugin: https://github.com/intel/intel-device-plugins-for-kubernetes/pull/395
