### ISSUE TITLE
Publish One Device Operator in Operator Hub

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#385]
Publish One Device Operator in Operator Hub

**Comment by rojkov** [comment]
I have to pause this task due to https://github.com/operator-framework/operator-lifecycle-manager/issues/1315#issuecomment-692597350

**Comment by rojkov** [comment]
The progress can be tracked at https://github.com/operator-framework/community-operators/pull/2750 now.

**Comment by msivosuo** [comment]
@rojkov - could we ping operator-framework people on this to get some traction?

**Comment by rojkov** [comment]
I've managed to find to [this instruction](https://operator-framework.github.io/community-operators/#test-your-operator-before-submitting-a-pr) on how to reproduce the CI tests locally. But I'm busy with a QAT engine issue ATM. Will try it later.

**Comment by pohly** [comment]
@avalluri has added CI testing of the PMEM-CSI operator. He can provide further pointers and help in case that you need it.

**Comment by rojkov** [comment]
Closing as https://github.com/operator-framework/community-operators/pull/2750 got merged.
