### ISSUE TITLE
[linter] Enable wsl check

### ISSUE THREAD

**Issue by rojkov** [intel/intel-device-plugins-for-kubernetes#392]
in ${PROJECT_ROOT}/.golangci.yml to improve readability.

**Comment by kad** [comment]
Suggestion: maybe check the `gocognit` that seems to be doing same as wsl + more.

**Comment by rojkov** [comment]
@kad it's enabled already (see https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/.golangci.yml#L15)
I even had to relax it a bit to make it pass. The problem was 
```
pkg/topology/topology.go:257:1: cognitive complexity 31 of func `GetTopologyInfo` is high (> 30) (gocognit)
func GetTopologyInfo(devs []string) (*pluginapi.TopologyInfo, error) {
```

**Comment by mythi** [comment]
With the current `main` we get 50 hits which are mostly about adding empty lines. I don't think this is meaningful item to track/add.

@rojkov are you fine closing?

**Comment by rojkov** [comment]
After a bit of internal struggle... Yes, I'm fine. :)

**Comment by bart0sh** [comment]
Can we fix those 50 hits or I'm missing something?

**Comment by bart0sh** [comment]
I started to work on it and after fixing bunch of hundreds I realized that the check outputs only 50 issues by default :)
