### ISSUE TITLE
DSA K8s Support Study

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#393]
-Study DSA K8s Device Support.
-Define deliverables and plan how to deliver

https://01.org/blogs/2019/introducing-intel-data-streaming-accelerator

**Comment by msivosuo** [comment]
@rojkov - good first step would be to be in touch with driver developers on how to get started.

**Comment by msivosuo** [comment]
@bart0sh - do you think you could you take a look at this in July/August? We needed to move @rojkov to another study.

**Comment by bart0sh** [comment]
@mythi sure, I'll try.
