### ISSUE TITLE
Move to sphinx-based documentation

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#399]
- [x]  Coordinate with tech writers on how to move to sphinx-based documentation
- [ ]  Coordinate tech writer documentation review
- [ ]  Deploy new documentation format

**Comment by msivosuo** [comment]
See #446

**Comment by msivosuo** [comment]
Implemented by #454

**Comment by mythi** [comment]
https://intel.github.io/intel-device-plugins-for-kubernetes/README.html
