### ISSUE TITLE
harmonize imagePullPolicy usage

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#400]
it looks our `imagePullPolicy` usage isn't consistent between the plugins. Define a setting/kustomize overlay that suits all the plugins.

**Comment by mythi** [comment]
Based on our experience, `imagePullPolicy: Always` for the master branch is the least error prone.

The opens are:
- is this OK for the release branches too?
- should we document how to add a kustomize overlay to change it if `Always` is not desired?

**Comment by bart0sh** [comment]
I think it's ok to have 'Always' policy for all branches.

**Comment by bart0sh** [comment]
> should we document how to add a kustomize overlay to change it if Always is not desired?

That would be great to have it documented. It would be even better to have ready to use kustomize overlays to switch to IfNotPresent policy.
