### ISSUE TITLE
Publish 0.20 version of Device Plugin Operator on Operator Hub

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#444]
Publish new version (0.20) of Device Plugin operator on Operator Hub, including DSA support.

https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/DEVEL.md#how-to-publish-a-new-version-of-the-intel-device-plugins-operator

**Comment by bart0sh** [comment]
@mythi @rojkov Created PR: https://github.com/operator-framework/community-operators/pull/3573
please, review

**Comment by mythi** [comment]
@bart0sh LGTM, one nit: maybe add dsa to CSV keywords.

**Comment by bart0sh** [comment]
@mythi thank you for the review. will do.

BTW, some tests fail on the plugin. If you know how to fix that please let me know

**Comment by bart0sh** [comment]
Done: https://operatorhub.io/operator/intel-device-plugins-operator

**Comment by msivosuo** [comment]
Great to see it published, thanks! Any reason we do not have YAML example for DSA? For other devices there's one.

**Comment by bart0sh** [comment]
No particular reason. Thanks for pointing out. Will fix.

**Comment by bart0sh** [comment]
Here is the fix: https://github.com/operator-framework/community-operators/pull/3590
I'll need to convince maintainers that this is a cosmetic change, otherwise we'll have to release 0.20.1 or wait until 0.21.0 is ready
