### ISSUE TITLE
update to k8s 1.19 APIs

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#452]

**Comment by rojkov** [comment]
K8s 1.19 has updated dependency on `github.com/go-logr/logr` to v0.2.0, but the latest released `sigs.k8s.io/controller-runtime` (0.6.3) still depends on logr v0.1.0.

controller-runtime 0.7.0, which seems to have the dependency updated, hasn't been released yet.

This prevents us from updating to k8s 1.19.

**Comment by mythi** [comment]
> controller-runtime 0.7.0, which seems to have the dependency updated, hasn't been released yet.

Let's wait 0.7.0. It looks it's not too far away...

**Comment by mythi** [comment]
> controller-runtime 0.7.0, which seems to have the dependency updated, hasn't been released yet.

@rojkov can you start with a draft PR that updates k8s 1.19 and controller-runtime 0.7.0-alpha4. Or would `Replace` v0.1.0 -> v0.2.0 work?

**Comment by rojkov** [comment]
Ok. I'll start with moving to controller-runtime 0.7.0-alpha4. It seems to be a safer bet.

**Comment by rojkov** [comment]
Now all deps seem to resolve ok. I pushed the new `go.mod` to my private `release-0.19` branch. The next step is to make the code compile.
