### ISSUE TITLE
amend operator samples with full CRDs and add kustomization

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#479]
End user feedback:
The current samples only contain the image in the spec – it might be useful to have a sample with other fields (eg dpdk driver, kernel driver, num of VFs etc) already filled out so that the user knows what can be configured by looking at the sample

**Comment by mythi** [comment]
added need: make it possible to deploy sample CRs using kustomize

**Comment by rojkov** [comment]
What kind of kustomization is needed? Is it for the operator or plugins?
