### ISSUE TITLE
updates to clean-up non-inclusive language

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#499]
Meta-issue to track inclusive language updates

- [x] docs /cc @intelkevinputnam (can you help?)
- [ ] Dockerfiles (@mythi)
- [x]  run-dpdk-test (@mythi)
- [x] FGPA cri_hook test data, topology (@bart0sh)
- [x] master -> main (all) (agreed to target the change during christmas time)

**Comment by intelkevinputnam** [comment]
I've been trying out https://github.com/get-woke/woke to check for inclusive language problems. Found no issues with the docs.

**Comment by mythi** [comment]
@intelkevinputnam we wanted ask help updating the docs when we rename 'master' to 'main'

**Comment by mythi** [comment]
@intelkevinputnam is that something you could help with?

**Comment by intelkevinputnam** [comment]
@mythi Since the new year my focus has shifted to tools development. @dougtw may be able to help.

**Comment by mythi** [comment]
done!
