### ISSUE TITLE
move to static and stripped binaries, use distroless

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#516]
do you see problems with these `-ldflags`:

```
-w
	Omit the DWARF symbol table.
-s
	Omit the symbol table and debug information.
```

also, when building without `CGO_ENABLED` we can build the plugins static and move to use distroless:static

**Comment by uniemimu** [comment]
Only if those have an impact on the issue reporting by reducing trace information. Considering security those sound good.
