### ISSUE TITLE
qat_plugin: additional review comments

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#55]
I've tested the QAT plug-in on my host and read the code a little bit. Here's my observations/improvement ideas:

- while re-running the plug-in multiple times, I eventually run "out of resources" because the devices remain bound to the dpdk user IO driver. The driver should probably implement:
``` for i in `ls -d /sys/bus/pci/drivers/vfio-pci/0000:*`; do echo `basename $i` > /sys/bus/pci/drivers/vfio-pci/unbind; done``` (for the given ```dpdk-driver```) in its init (Edit: this might be trickier than just unbind)
- ```maxNumdevice``` check looks wrong. 1) the loop gives ```maxNumdevice```from each kernel driver resulting N_drivers * ```maxNumdevice``` devices. 2) the loop continues for all files even if ```maxNumdevice``` is already reached

**Comment by mythi** [comment]
@swatisehgal I wrote some review feedback still.

**Comment by swatisehgal** [comment]
Thanks @mythi for your feedback!! There has been some code refactoring done recently which takes care of the maxNumdevice issue that you have pointed out. And as far as the out of resource issue is concerned, I will have a look into that to see what can be done to gracefully handle this case. You are right that this is tricker than unbind as we need to be aware that there might be devices bound to the dpdk driver configured with the intention to be used on the host and are not assigned to the kubernetes for device allocation. So randomly unbinding those devices to the kernel would not be correct.  I think for the time being we can update the README to mention this limitation while we work towards overcoming this.

**Comment by mythi** [comment]
ping @MCamp859. FYI, see the proposed README updates.

@swatisehgal perhaps the plugin could log out the devices it binds for easier manual 'recovery'.

**Comment by rojkov** [comment]
Is there a way to detect the devices that are already in use on the host so the plugin could exclude them from exposing?

**Comment by mythi** [comment]
@rojkov the plugin already "excludes" them (them= host dpdk users): it only looks devices that are bound to the QAT kernel driver module and re-binds those to UIO/vfio-pci.

**Comment by rojkov** [comment]
@mythi This isn't the case after my refactoring: now it looks for devices that are bound to kernel and DPDK drivers.

If the only indication of the fact the device is taken by some other process is that it's bound to uio/vfio-pci then we'd better add unbinding upon the plugin's exit. Though I can't say that's a perfect solution because I feel it's prone to device leakages.

**Comment by rojkov** [comment]
@mythi True. My assumption was that we don’t care about the use case where some devices are taken by host processes. And the FPGA plugin has been developed without this use case in mind.

**Comment by mythi** [comment]
Obsoleted by #145 and #146
