### ISSUE TITLE
consider deprecating fpga_admissionwebhook

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#578]
the fpga webhook functionality is available in two places: it's part of the operator and as a stand-alone webhook image. if we want to prioritize the operator workflow, the latter is redundant.

Discuss & agree the future of fpga_admissionwebhook

**Comment by kad** [comment]
That would practically mean that it would be impossible to use FPGA plugin without using operator.
Does that make sense? I mean if we would have customers who don't want for some reason to use operator.

**Comment by mythi** [comment]
the consensus is that we keep it, closing
