### ISSUE TITLE
run kind tests with github actions

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#613]
- [ ] fpga admission webhook
- [ ] sgx admission webhook
- [ ] deploy operator

using https://github.com/marketplace/actions/kind-kubernetes-in-docker-action

**Comment by mythi** [comment]
maybe add:
https://github.com/helm/kind-action

**Comment by msivosuo** [comment]
@hj-johannes-lee - could you take a look at this one, based on the plan looks like you have free cycles in this period.

**Comment by hj-johannes-lee** [comment]
@msivosuo Ok.! I was just planning to solve projects here first and then focus more on the kubernetes issue I am assigned to,, but let me do.!
