### ISSUE TITLE
Support for other FPGA vendor and product ids

### ISSUE THREAD

**Issue by rmr-silicom** [intel/intel-device-plugins-for-kubernetes#618]
Within utils.go, only the intel vendor id is used. How can other vendor and product ids be added to support?

**Comment by bart0sh** [comment]
FPGA plugin supports only 2 Intel FPGA cards at the moment:
- Intel Arria 10
- Intel Stratix 10

**Comment by rmr-silicom** [comment]
Thanks for the response. I am adding support for a FPGA card. Another question I have...

https://github.com/OPAE/opae-sdk

What is the project difference? From my initial reading, this project and the opae-sdk kinda do the same thing.

**Comment by bart0sh** [comment]
OPAE SDK is a set of libraries to work with FPGA. This project is a device plugin that enables various Intel accelerator devices in Kubernetes clusters. You can read about Kubernetes device plugins here: https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/

**Comment by rmr-silicom** [comment]
Got it. I am actually implementing an openshift operator for an FPGA PCIe device base on the Stratix 10, and have been pointed into the OPAE SDK direction, but it seems from a kubernetes point of view, this operator/golang pkg is where i should be using my time?

**Comment by rojkov** [comment]
> it seems from a kubernetes point of view, this operator/golang pkg is where i should be using my time?

Yes, this project also provides a K8s operator for Intel FPGAs (and some other Intel HW). The latest release has been published at https://operatorhub.io/operator/intel-device-plugins-operator. Your contributions are welcome.

**Comment by mythi** [comment]
> Your contributions are welcome.

@rmr-silicom or any feedback if the existing functionality does not meet your use-cases.

**Comment by mythi** [comment]
@rmr-silicom did we answer your question and we can close this?
