### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [intel/intel-device-plugins-for-kubernetes#633]
Hello,

In order to combat dockerhub's imposed rate limits it would be great to host these images on ghcr or quay.io. Are there on any thoughts from the community on this initiation?

**Comment by mythi** [comment]
The device plugins release images are not updated that often and when combined with `IfNotPresent` (or even `Never`) `imagePullPolicy`, it should have minimal impact to your pull quota (the quota is IP based and not image based).

**Comment by onedr0p** [comment]
Say you need to bootstrap a cluster with 10 nodes, each one using this Docker image. Now stack up all the other applications in your cluster also pulling from Dockerhub... it's VERY easy to hit their rate limits.

Yes there are ways to get around this on my side but it requires setting up a pull thru cache, but why not help solve the problem for everyone by pushing to an additional registry? GHCR is very easy to publish images to.

**Comment by mythi** [comment]
Our device plugins images are now with the "verified publisher" badges and so free from any pull limits. Closing.

**Comment by onedr0p** [comment]
@mythi it looks like being part of the "Verified Publishers" only prevents your team from rate limits.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/213795/214117113-209e0747-8fac-4823-808d-1d5443c59859.png">
