### ISSUE TITLE
operator reconciler update fails sporadically

### ISSUE THREAD

**Issue by uniemimu** [intel/intel-device-plugins-for-kubernetes#663]
The operator Update call fails sporadically at least after the gpu controller has run, but potentially after any of the controllers

`E0622 10:15:07.773355       1 reconciler.go:118] intel-device-plugins-manager/controller/gpudeviceplugin "msg"="unable to update DaemonSet" "error"="Operation cannot be fulfilled on daemonsets.apps \"intel-gpu-plugin-fzn2t\": the object has been modified; please apply your changes to the latest version and try again" "name"="intel-gpu-plugin" "namespace"="" "reconciler group"="deviceplugin.intel.com" "reconciler kind"="GpuDevicePlugin" "DaemonSet"={"kind":"DaemonSet","apiVersion":"apps/v1","metadata":{"name":"intel-gpu-plugin-fzn2t","generateName":"intel-gpu-plugin-","namespace":"inteldeviceplugins-system","uid":"e4d331f4-279a-4b7a-b7ae-9d60865acb60","resourceVersion":"294160","generation":35,"creationTimestamp":"2021-06-22T10:05:59Z","labels":{"app":"intel-gpu-plugin"},"annotations":{"deprecated.daemonset.template.generation":"35"},"ownerReferences":[{"apiVersion":"deviceplugin.intel.com/v1","kind":"GpuDevicePlugin","name":"intel-gpu-plugin","uid":"5d80e18a-7319-4ae4-ae0f-a97beddf17c2","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"intel_deviceplugin_operator","operation":"Update","apiVersion":"apps/v1","time":"2021-06-22T10:05:59Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:deprecated.daemonset.template.generation":{}},"f:generateName":{},"f:labels":{".":{},"f:app":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"5d80e18a-7319-4ae4-ae0f-a97beddf17c2\"}":{".":{},"f:apiVersion":{},"f:blockOwnerDeletion":{},"f:controller":{},"f:kind":{},"f:name":{},"f:uid":{}}}},"f:spec":{"f:revisionHistoryLimit":{},"f:selector":{},"f:template":{"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"intel-gpu-plugin\"}":{".":{},"f:args":{},"f:env":{".":{},"k:{\"name\":\"NODE_NAME\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:fieldRef":{".":{},"f:apiVersion":{},"f:fieldPath":{}}}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:securityContext":{".":{},"f:readOnlyRootFilesystem":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/dev/dri\"}":{".":{},"f:mountPath":{},"f:name":{},"f:readOnly":{}},"k:{\"mountPath\":\"/sys/class/drm\"}":{".":{},"f:mountPath":{},"f:name":{},"f:readOnly":{}},"k:{\"mountPath\":\"/var/lib/kubelet/device-plugins\"}":{".":{},"f:mountPath":{},"f:name":{}}}}},"f:dnsPolicy":{},"f:initContainers":{".":{},"k:{\"name\":\"intel-gpu-initcontainer\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:securityContext":{".":{},"f:readOnlyRootFilesystem":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/etc/kubernetes/node-feature-discovery/source.d/\"}":{".":{},"f:mountPath":{},"f:name":{}}}}},"f:nodeSelector":{".":{},"f:kubernetes.io/arch":{}},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{},"f:volumes":{".":{},"k:{\"name\":\"devfs\"}":{".":{},"f:hostPath":{".":{},"f:path":{},"f:type":{}},"f:name":{}},"k:{\"name\":\"kubeletsockets\"}":{".":{},"f:hostPath":{".":{},"f:path":{},"f:type":{}},"f:name":{}},"k:{\"name\":\"nfd-source-hooks\"}":{".":{},"f:hostPath":{".":{},"f:path":{},"f:type":{}},"f:name":{}},"k:{\"name\":\"sysfs\"}":{".":{},"f:hostPath":{".":{},"f:path":{},"f:type":{}},"f:name":{}}}}},"f:updateStrategy":{"f:rollingUpdate":{".":{},"f:maxUnavailable":{}},"f:type":{}}}}},{"manager":"kube-controller-manager","operation":"Update","apiVersion":"apps/v1","time":"2021-06-22T10:15:01Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:currentNumberScheduled":{},"f:desiredNumberScheduled":{},"f:numberAvailable":{},"f:numberReady":{},"f:observedGeneration":{},"f:updatedNumberScheduled":{}}}}]},"spec":{"selector":{"matchLabels":{"app":"intel-gpu-plugin"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"intel-gpu-plugin"}},"spec":{"volumes":[{"name":"devfs","hostPath":{"path":"/dev/dri","type":""}},{"name":"sysfs","hostPath":{"path":"/sys/class/drm","type":""}},{"name":"kubeletsockets","hostPath":{"path":"/var/lib/kubelet/device-plugins","type":""}},{"name":"nfd-source-hooks","hostPath":{"path":"/etc/kubernetes/node-feature-discovery/source.d/","type":"DirectoryOrCreate"}}],"initContainers":[{"name":"intel-gpu-initcontainer","image":"registry.local/intel-gpu-initcontainer:1.20.5","resources":{},"volumeMounts":[{"name":"nfd-source-hooks","mountPath":"/etc/kubernetes/node-feature-discovery/source.d/"}],"imagePullPolicy":"IfNotPresent","securityContext":{"readOnlyRootFilesystem":true}}],"containers":[{"name":"intel-gpu-plugin","image":"registry.local/intel-gpu-plugin:1.20.5","args":["-v","2","-shared-dev-num","300"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}}],"resources":{},"volumeMounts":[{"name":"devfs","readOnly":true,"mountPath":"/dev/dri"},{"name":"sysfs","readOnly":true,"mountPath":"/sys/class/drm"},{"name":"kubeletsockets","mountPath":"/var/lib/kubelet/device-plugins"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"readOnlyRootFilesystem":true}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"kubernetes.io/arch":"amd64"},"securityContext":{},"schedulerName":"default-scheduler"}},"updateStrategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1}},"revisionHistoryLimit":10},"status":{"currentNumberScheduled":1,"numberMisscheduled":0,"desiredNumberScheduled":1,"numberReady":1,"observedGeneration":34,"updatedNumberScheduled":1,"numberAvailable":1}}
E0622 10:15:07.773496       1 controller.go:302] intel-device-plugins-manager/controller/gpudeviceplugin "msg"="Reconciler error" "error"="Operation cannot be fulfilled on daemonsets.apps \"intel-gpu-plugin-fzn2t\": the object has been modified; please apply your changes to the latest version and try again" "name"="intel-gpu-plugin" "namespace"="" "reconciler group"="deviceplugin.intel.com" "reconciler kind"="GpuDevicePlugin" 
`

It may take many changes to the custom resource to be executed in order for the problem to arise, this does not happen every time. I was fiddling with the shared-dev-num arg and went back-and-forth between two values.

Further rounds of the reconciler will successfully update the object, as the object is always refreshed. Thus this is mostly a cosmetic issue, but it could perhaps be avoided by using other update mechanisms such as patching.

**Comment by msivosuo** [comment]
Not happening anymore -> closing.
