### ISSUE TITLE
It is hard to find the info on how to specify an Intel device feature requirement in a workload spec

### ISSUE THREAD

**Issue by cathyhongzhang** [intel/intel-device-plugins-for-kubernetes#711]
We have these device features: GPU, FPGA, QAT, SGX, DSA, VPU, but it is hard to find info on how a developer needs to specify the feature requirement for its workload. 
We need to make the application developer's life easier, i.e. make it easy to understand the benefit of each feature and to find info on how to specify the feature requirement for a workload spec. As we discussed, a new developer/user targeted document will be created for this purpose. Then we will add a reference link to this document in the public K8S device plugin page, https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/

**Comment by msivosuo** [comment]
Moved to backlog, QAT resource naming will change in near future. Let's as a quick improvement point to demo deployments in our demo section for device resource names.
