### ISSUE TITLE
FPGA: support multiple FPGA devices

### ISSUE THREAD

**Issue by bart0sh** [intel/intel-device-plugins-for-kubernetes#72]
FPGA plugin, Admission Webhook and CRI hook currently support only one FPGA device. They should be extended to support multiple devices. This will help to support more complex FPGA workflows that use more than one accelerated function.

**Comment by rojkov** [comment]
I've added support for multiple devices per container to webhook in https://github.com/rojkov/intel-device-plugins-for-kubernetes/tree/multiple-fpgas.

The CRI-O hook is the next step.
