### ISSUE TITLE
Investigate github environments for project management purposes

### ISSUE THREAD

**Issue by bart0sh** [intel/intel-device-plugins-for-kubernetes#720]
Github Environments and actions provide a good opportunity to automate our development and release process.
We may want to use it for this project.

Here is an example of a workflow definition using GH Environments and actions: https://timheuer.com/blog/add-approval-workflow-to-github-actions/

In our case workflow steps could be different, but the idea is the same - to use github CI/CD functionality to automate our workflows (development, release, etc)

**Comment by mythi** [comment]
cleanup
