### ISSUE TITLE
FPGA: create Ansible playbook

### ISSUE THREAD

**Issue by bart0sh** [intel/intel-device-plugins-for-kubernetes#73]
Due to complexity of the plugin setup and many components involved it would make sense to automate its deployment by creating ansible playbook.

**Comment by bart0sh** [comment]
This can be used as a start for this task: [Using kubeadm with CRI-O](https://www.projectatomic.io/blog/2017/06/using-kubeadm-with-cri-o/)

The guide includes instructions and links to the [Ansible playbook](https://github.com/cri-o/cri-o-ansible) that deploys CRI-O. We just need to add FPGA plugin specifics to it.

**Comment by mythi** [comment]
@bart0sh @rojkov with kustomize in place and the fact that drivers issues are covered, perhaps we can close this?

**Comment by bart0sh** [comment]
makes sense. closing
