### ISSUE TITLE
Configure CI to schedule regular e2e job runs

### ISSUE THREAD

**Issue by bart0sh** [intel/intel-device-plugins-for-kubernetes#763]
Currently e2e jobs can only be run manually.
It makes sense to schedule them to run at least once per day using ['schedule' events](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events) and sending e-mail to the list of maintainers if tests fail.

**Comment by mythi** [comment]
@bart0sh +1
