### ISSUE TITLE
OCP:  Operator Certification Step 1: Operator Container Image and plugin Container Image Cerificate 

### ISSUE THREAD

**Issue by Walnux** [intel/intel-device-plugins-for-kubernetes#775]
According to the OCP document:
https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/program-on-boarding/certification-workflow
we need to certificate the operator Container Image and plugin Container Image.

- [x] Build UBI based Images
- [x] Check the New Image License
- [ ] Image Certificate

**Comment by chaitanya1731** [comment]
Update 1 - 
Started working on certifying application container image. Started with intel-sgx-initcontainer image.. Tried scanning the image on redhat certification portal. It keeps loading for a few seconds and disappears.
We need to convert our current image to UBI base image..
Base image requirements -
- All images to be deployed in a cluster should be built on the same base image or images with the same Linux libraries.
- To ensure that the base image is compatible with the worker node’s operating system, the Linux libraries in the base image and the operating system running the worker nodes should be compatible versions of the same Linux distribution.
- The base image should be freely redistributable across public and private registries without requiring any paid licensing.
- The base image should run well in both Kubernetes and OpenShift.
- While a Kubernetes worker node can run a variety of Linux distributions, an OpenShift worker node requires a Linux distribution that is compatible with Red Hat Enterprise Linux.

**Comment by Walnux** [comment]
The Image certification & release process is very clear. We can close this issue now.
