### ISSUE TITLE
OCP: Bundle Image for OCP OLM (Operator Lifecycle Manager), Certification, testing and releasing

### ISSUE THREAD

**Issue by Walnux** [intel/intel-device-plugins-for-kubernetes#776]
Build the proper operator Bundle Image for OCP OLM. 

- [x] 1. Meets the Webhook requirements and removes the dependent on cert-Manager. 

- [x] 2. Figure out the proper way to run NFD through NFD-operator: The NFD should run by this operator or by cluster user/adminstrator through NFD-operator? 
- [x] 3. Build Bundle Image and run on OCP OLM 
- [ ] 4. push the Bundle image to the proper repository
- [ ] 5. Do the Certification and testing on this bundle image see https://github.com/intel/intel-device-plugins-for-kubernetes/issues/776
- [ ] 6. Add the proper release notes and readme for the release of the operator on OCP
- [ ] ....

**Comment by Walnux** [comment]
Below task is done
2. Figure out the proper way to run NFD through NFD-operator: The NFD should run by this operator or by cluster user/adminstrator through NFD-operator?
for detail see task/issue https://github.com/intel/intel-device-plugins-for-kubernetes/issues/781

**Comment by Walnux** [comment]
For task 1, operator-sdk can create the bundle image with CSV file using OLM webhook, please reference the related CSV file.
And The operator can start properly without crt-manager.
You can simply run operator using below command on OCP
`$ operator-sdk run bundle docker.io/walnuxdocker/intel-device-plugins-operator-bundle:0.22.0    `

**Comment by Walnux** [comment]
the bundle image has been upgraded the v0.23.0
to run the image to install operator use below command
operator-sdk run bundle docker.io/walnuxdocker/intel-device-plugins-operator-bundle:0.23.0

**Comment by mythi** [comment]
@Walnux can that be generated using `make bundle`?

**Comment by Walnux** [comment]
@mythi yes. it is created from make bulndle.
