### ISSUE TITLE
OCP: intel-device-plugins operator with SGX support on Red Hat OCP (OpenShift Container Platform)

### ISSUE THREAD

**Issue by Walnux** [intel/intel-device-plugins-for-kubernetes#777]
The goal of the task is to release the intel-device plugins operator with SGX support on Red Hat OCP. The subtasks include

- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/776
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/852
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/778
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/775
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/774
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/762
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/780
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/781

**Comment by mythi** [comment]
@Walnux can we have only one issue to track the work and then create a list of items to track sub-tasks?

**Comment by mythi** [comment]
all the tasks are complete. closing
