### ISSUE TITLE
OCP: deploy NFD through NFD-operator for SGX

### ISSUE THREAD

**Issue by Walnux** [intel/intel-device-plugins-for-kubernetes#781]
After the SGX detect fixing got merged into OCP see https://github.com/intel/intel-device-plugins-for-kubernetes/issues/780
We need work out the solution to deploy NFD through NFD-operator on OCP.

According to feed back from https://github.com/openshift/cluster-nfd-operator/issues/231 by @ArangoGutierrez

We need firstly add required nfd-operator CRD in CSV file. like what has been done in SRO project see 
https://github.com/openshift/special-resource-operator/blob/master/config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml#L28

- [ ] And then we should provide the user (cluster-administrator) the YAML file to create the CR and deploy the NFD and enable the SGX detecting.
- [ ] Provide the NFD-Operator CR like https://docs.openshift.com/container-platform/4.9/hardware_enablement/psap-node-feature-discovery-operator.html to Deploy NFD with SGX support. Should we put it in documentation or need to push to upstream?

**Comment by mregmi** [comment]
@mythi do you think we can provide a sample NFD CR file for SGX and other operators like this in this repo? if yes we can create a pull request for it.

**Comment by mythi** [comment]
> @mythi do you think we can provide a sample NFD CR file for SGX and other operators like this in this repo?

That works for me. See `deployments/nfd`. Try to move to use `NodeFeatureRule` since the NFD operator adds the CRD for it and we maintain them in this repo also.

**Comment by Walnux** [comment]
https://github.com/intel/intel-device-plugins-for-kubernetes/pull/932 is used to fix this issue.
