### ISSUE TITLE
doc: SGX device plugin config parameters have identical  descriptions 

### ISSUE THREAD

**Issue by mkbhanda** [intel/intel-device-plugins-for-kubernetes#782]
See https://intel.github.io/intel-device-plugins-for-kubernetes/cmd/sgx_plugin/README.html

Flag	Argument	Meaning
-enclave-limit	int	the number of containers per node allowed to use /dev/sgx/enclave (default: 20)
-provision-limit	int	the number of containers per node allowed to use /dev/sgx/provision (default: 20)

**Comment by mythi** [comment]
They are different in that they point to different device nodes. The description has other issues though, fixed in #783
