### ISSUE TITLE
idxd: Update idxd-config-initcontainer

### ISSUE THREAD

**Issue by hj-johannes-lee** [intel/intel-device-plugins-for-kubernetes#819]
- [ ] Current implementation does not allow it running as read-only. It needs to be fixed.
- [ ] update `accel-config` and start using the new `load-config` parameters to enable WQs
- [ ] make provisioning config `configMap` readonly with `DefaultMode` set for the volume

**Comment by mythi** [comment]
@ozhuraki this issue tracks pending `idxd-config` updates/fixes

**Comment by mythi** [comment]
@hj-johannes-lee the third task captures what we discussed yesterday so separate issue is not needed

**Comment by hj-johannes-lee** [comment]
@mythi Thanks.! :)
