### ISSUE TITLE
DSA container failed due to operation not permitted

### ISSUE THREAD

**Issue by yengliong** [intel/intel-device-plugins-for-kubernetes#919]
Hi, I am trying to run DSA plugin on my Ubuntu using kubectl command below. 
`kubectl apply -k https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/dsa_plugin?ref=main
`

The command deploys the daemonset but the pod is in **CreateContainerError** status. 

NAME                           READY   STATUS                 RESTARTS        AGE
intel-dsa-plugin-d4qgj   0/1     CreateContainerError   0               4s

By checking on the pod message, there is an error mentioning about operation not permitted. 

![image](https://user-images.githubusercontent.com/46098822/158296472-3b307ad1-ae07-47e4-8a62-790b0966f727.png)

Any ideas?

**Comment by mythi** [comment]
> Any ideas?

Is the `idxd` module loaded?

**Comment by yengliong** [comment]
Thank you for pointing that out, I didn't load idxd module.
Can I know how to get it?

**Comment by mythi** [comment]
@yengliong it's part of mainline kernel, we have been using 5.15+ kernels.

**Comment by yengliong** [comment]
After loading idxd driver, the container is running.
I want to verify the plugin with command below. 
`kubectl get nodes -o go-template='{{range .items}}{{.metadata.name}}{{"\n"}}{{range $k,$v:=.status.allocatable}}{{"  "}}{{$k}}{{": "}}{{$v}}{{"\n"}}{{end}}{{end}}' | grep '^\([^ ]\)\|\(  dsa\)'`

The output only shows me **node1**.  
I didn't see the information like _dsa.intel.com/wq-user-dedicated_ or _dsa.intel.com/wq-user-shared_.
Btw, my kernel is 5.11.0-16. Maybe the kernel version causes the issue?

**Comment by mythi** [comment]
> I didn't see the information like dsa.intel.com/wq-user-dedicated or dsa.intel.com/wq-user-shared.

`idxd` does not create any of these automatically but they must be configured using `accel-config`. We provide an initcontainer that provisions a default configuration. DSA README documents it.

**Comment by mythi** [comment]
@yengliong OK to close?

**Comment by yengliong** [comment]
Hi @mythi Yes, please go ahead to close it. I will go through the DSA README, thank you :)

**Comment by mythi** [comment]
@yengliong Thanks! Please re-open or submit another issue if you run into problems.
