### ISSUE TITLE
e2e: add tests to deploy and test plugins with the operator

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#931]
currently, our e2e tests do not test anything with the operator based flow. Add tests that install the operator, deploy plugins and tests them using the BMAAS `e2e-*` workflows.

**Comment by msivosuo** [comment]
Slow progress, pr estimated to be submitted in WW39. Still no PR?

**Comment by msivosuo** [comment]
@ozhuraki - please submit the draft pr for this by the end of the week as agreed.
