### ISSUE TITLE
doc: correct path for the DSA provisioning config in ConfigMap

### ISSUE THREAD

**Issue by ttzeng** [intel/intel-device-plugins-for-kubernetes#941]
Please to confirm the correct path for the `dsa.conf` and `dsa-node1.conf` provided in below instruction in this [section](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/dsa_plugin/README.md#deploy-with-initcontainer-and-provisioning-config-in-the-configmap). If these files are from the configMap mounted volume, should they be from `/idxd-init/conf`. If these are from the external files, `dsa-node1.conf` is not presented in the demo folder?
```
$ kubectl create configmap --namespace=inteldeviceplugins-system intel-dsa-config --from-file=demo/dsa.conf --from-file=demo/dsa-node1.conf --dry-run=client -o yaml > dsa-config.yaml
```

**Comment by mythi** [comment]
@ttzeng yes, `dsa-node1.conf` is missing. Also, I think the sample command should be updated to actually create the configmap.
