### ISSUE TITLE
Validate QAT device plugin on simulated SPR

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#950]
- [ ]  Validate (e2e) Intel QAT Device Plugin in the simulation (Simics) environment

**Comment by mythi** [comment]
Some implementation notes:

- `4xxx` (in this simulated env) is not yet supported by the `crypto-perf` image
- (`crypto-perf`  expects CPU manager with dedicted CPUs and HugePages)
- we could also have a new set of e2e tests for `4xxx` that uses `openssl-qat-engine`. That image is up-to-date.

**Comment by mythi** [comment]
> * `4xxx` (in this simulated env) is not yet supported by the `crypto-perf` image

this is not a problem anymore because we have new enough DPDK: `EAL: RTE Version: 'DPDK 21.11.1'`
