### ISSUE TITLE
doc: [dsa] Dockerfile is downloaded but not used in the screencast file

### ISSUE THREAD

**Issue by ttzeng** [intel/intel-device-plugins-for-kubernetes#969]
Though I don't have the hardware platform to try out, though this screencast file `screencast-dsa-accel-config.sh` seems to work, but it downloads a Dockerfile but not uses it, which looks a redundancy.
```
command 'curl https://raw.githubusercontent.com/intel/intel-device-plugins-for-kubernetes/main/demo/dsa-accel-config-demo/Dockerfile' 100
```

**Comment by mythi** [comment]
it's on purpose to show the content of the image that is used.
